import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_FR: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calories",
            protein_g: "Protéines",
            carbs_g: "Glucides",
            fat_g: "Lipides",
            sugar_g: "Sucre",
            alcohol_g: "Alcool",
            caffeine_mg: "Caféine",
            fiber_g: "Fibres",
            water_ml: "Eau",
        },
        noGoalSet: "aucun objectif défini",
        atLimit: "à la limite",
        floorUnder: "restant",
        ceilingUnder: "de marge",
        over: "en trop",
        limitPrefix: "limite",
        ofPrefix: "sur",
        drinkLabels: { us: "verres US", uk: "unités UK" },
        noneLogged: "aucun enregistré",
        tapHint: "Touchez une valeur pour voir les repas correspondants",
        showMealsContributed: "Afficher les repas qui y ont contribué.",
        byMealTitle: "{label} par repas",
        closeBreakdown: "Fermer le détail",
        noMealsContributed: "Aucun repas enregistré n'a contribué à {label}.",
        untitledMeal: "Repas sans titre",
        moreMeals: {
            one: "+ {n} repas plus petit",
            other: "+ {n} repas plus petits",
        },
    },
    nutritionSummary: {
        title: "Résumé nutritionnel",
        loading: "Chargement de votre résumé nutritionnel…",
        empty: "Aucun repas ni eau enregistré sur cette période.",
        caloriesPerDay: "Calories / jour",
        avg: "moy.",
        goal: "objectif",
        dailyAvgLoggedDays: "Moy. quotidienne · jours enregistrés",
        total: "Total",
        daysLogged: {
            one: "{n} jour enregistré",
            other: "{n} jours enregistrés",
        },
        daysOfLogged: "{logged} jours enregistrés sur {span}",
        months: [
            "Jan",
            "Fév",
            "Mar",
            "Avr",
            "Mai",
            "Jun",
            "Jul",
            "Aoû",
            "Sep",
            "Oct",
            "Nov",
            "Déc",
        ],
    },
};
