import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_FR: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calories",
            protein_g: "Protéines",
            carbs_g: "Glucides",
            fat_g: "Lipides",
            sugar_g: "Sucre",
            alcohol_g: "Alcool",
            caffeine_mg: "Caféine",
            fiber_g: "Fibres",
            water_ml: "Eau",
        },
        noGoalSet: "aucun objectif défini",
        atLimit: "à la limite",
        floorUnder: "restant",
        ceilingUnder: "de marge",
        over: "en trop",
        limitPrefix: "limite",
        ofPrefix: "sur",
        drinkLabels: { us: "verres US", uk: "unités UK" },
        noneLogged: "aucun enregistré",
        caloriesToday: "Calories aujourd'hui",
        tapHint: "Touchez une valeur pour voir les repas correspondants",
        showMealsContributed: "Afficher les repas qui y ont contribué.",
        byMealTitle: "{label} par repas",
        closeBreakdown: "Fermer le détail",
        noMealsContributed: "Aucun repas enregistré n'a contribué à {label}.",
        untitledMeal: "Repas sans titre",
        moreMeals: {
            one: "+ {n} repas plus petit",
            other: "+ {n} repas plus petits",
        },
    },
    nutritionSummary: {
        title: "Résumé nutritionnel",
        loading: "Chargement de votre résumé nutritionnel…",
        empty: "Aucun repas ni eau enregistré sur cette période.",
        caloriesPerDay: "Calories / jour",
        chartAriaLabel: "Calories par jour sur la période sélectionnée",
        avg: "moy.",
        goal: "objectif",
        dailyAvgLoggedDays: "Moy. quotidienne · jours enregistrés",
        total: "Total",
        daysLogged: {
            one: "{n} jour enregistré",
            other: "{n} jours enregistrés",
        },
        daysOfLogged: "{logged} jours enregistrés sur {span}",
        months: [
            "Jan",
            "Fév",
            "Mar",
            "Avr",
            "Mai",
            "Jun",
            "Jul",
            "Aoû",
            "Sep",
            "Oct",
            "Nov",
            "Déc",
        ],
    },
    goalProgress: {
        title: "Progression de l'objectif",
        empty: "Aucune progression d'objectif à afficher.",
        nothingLoggedFor: "Rien d'enregistré pour le {date}.",
        thisDay: "ce jour",
        mealsCount: { one: "{n} repas", other: "{n} repas" },
        waterCount: { one: "{n} eau", other: "{n} eaux" },
        weightLabel: "Poids",
        weightNoneNoTarget:
            "Aucun poids enregistré pour l'instant. Enregistre-en un avec log_weight pour suivre ta progression.",
        weightNoneWithTarget:
            "Aucun poids enregistré pour l'instant. Enregistre-en un avec log_weight pour suivre ta progression vers ton objectif de {target}.",
        weightNoGoal:
            "Poids {reading} — aucun objectif défini. Définis-en un avec set_nutrition_goals pour voir la progression ici.",
        atTarget: "objectif atteint",
        toLose: "{amount} à perdre",
        toGain: "{amount} à prendre",
        lastLogged: "dernier enregistrement le {date}",
        weightAria: "Poids {current}, objectif {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Repas enregistré",
        titleUpdated: "Repas mis à jour",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "Tendances",
        empty: "Aucun repas ni eau enregistré sur cette période pour l'instant.",
        avgUnder: "en dessous",
        loggedOfTotal: "{logged}/{total} jours enregistrés",
        caloriesOverRange: "Calories par jour sur les {range} derniers jours",
        windowAriaLabel: "Fenêtre de tendance",
        rangeDaysAriaLabel: "{n} jours",
        avgAllDays: "Moy. {range} jours · tous les jours",
    },
    weightTrends: {
        title: "Poids",
        empty: "Aucun poids enregistré sur cette période pour l'instant.",
        rangeEmpty:
            "Aucune pesée sur les {range} derniers jours. Essaie une période plus large.",
        windowAriaLabel: "Fenêtre de tendance",
        rangeAriaLabel: "{n} derniers jours",
        chartAriaLabel: "Poids du {from} au {to}, dernier {latest}",
        latest: "Dernier",
        needTwo: "2 pesées minimum",
        sinceDate: "{change} depuis le {date}",
        weighIns: { one: "{n} pesée", other: "{n} pesées" },
        atTarget: "objectif atteint",
        toLose: "{amount} à perdre",
        toGain: "{amount} à prendre",
        target: "Objectif {value}",
        noTarget: "Aucun objectif défini",
    },
    importMeals: {
        stepFile: "Fichier",
        stepMap: "Associer les colonnes",
        stepPreview: "Aperçu",
        stepImport: "Importer",
        fieldLabels: {
            logged_at: "Date / heure",
            description: "Nom de l'aliment",
            meal_type: "Repas",
            calories: "Calories",
            protein_g: "Protéines (g)",
            carbs_g: "Glucides (g)",
            fat_g: "Lipides (g)",
            fiber_g: "Fibres (g)",
            sugar_g: "Sucre, total (g)",
            alcohol_g: "Alcool (g)",
            caffeine_mg: "Caféine (mg)",
            notes: "Notes",
            time: "Heure (colonne séparée)",
            deleted: "Indicateur de suppression",
            source_id: "ID du repas (depuis notre export)",
            timezone: "Fuseau horaire (depuis notre export)",
        },
        chooseExportHeading: "Choisis ton export",
        noToolsWarning:
            "Cet hôte ne permet pas à cette vue d'écrire dans ton journal. Demande à Claude d'importer le fichier à ta place — il peut le faire directement.",
        emailFallback:
            "Si demander à Claude ne fonctionne pas non plus, écris à {email}.",
        tzWarning:
            "Ton fuseau horaire n'est pas défini, les heures seront donc lues en UTC et pourraient tomber sur le mauvais jour. Demande d'abord à Claude de définir ton fuseau horaire.",
        dropChoose: "Choisis un fichier CSV",
        dropOr: "ou dépose-le ici",
        recognizedHint:
            "Les exports de MyFitnessPal, Cronometer, Lose It! et MacroFactor sont reconnus automatiquement. Rien n'est enregistré tant que tu n'as pas confirmé.",
        dateMapHint:
            "Associe une colonne de date ci-dessus pour voir comment une valeur de ton fichier est convertie.",
        dateNoneHint: "Cette colonne ne contient aucune date.",
        dateUnreadable:
            "{raw} → ne peut pas être lu comme {format}, les lignes de ce type seront donc ignorées",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Associe une colonne de calories ci-dessus pour voir comment une valeur de ton fichier est convertie.",
        energyNoneHint: "Cette colonne ne contient aucun nombre.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (aucune conversion)",
        dateAmbiguousWarning:
            "Le format de date n'a pas pu être déterminé à partir de ce fichier — ses dates peuvent être lues aussi bien avec le jour en premier qu'avec le mois en premier. Confirme le format utilisé par ton appli : un mauvais choix classe les repas au mauvais jour, sans générer d'erreur.",
        dateFormatLabel: "Format de date de ce fichier",
        dateFormatYmd: "Année-Mois-Jour",
        dateFormatDmy: "Jour/Mois/Année",
        dateFormatMdy: "Mois/Jour/Année",
        energyUnitLabel: "Unité d'énergie de la colonne calories",
        energyUnitKcal: "Calories",
        energyUnitKj: "Kilojoules",
        mapColumnsHeading: "Associer les colonnes",
        rowsCount: { one: "{n} ligne", other: "{n} lignes" },
        columnsCount: { one: "{n} colonne", other: "{n} colonnes" },
        delimiterLabel: "séparateur",
        tabLabel: "tabulation",
        notInFile: "(absent de ce fichier)",
        columnFallback: "colonne {n}",
        addedSugarNotice:
            "Ce fichier a une colonne de sucres ajoutés ({column}) mais aucune colonne de sucres totaux, donc Sucre n'a pas été associé. Le sucre est stocké comme sucres TOTAUX, y compris ceux naturellement présents dans les fruits et le lait, donc y associer les sucres ajoutés sous-estimerait chaque ligne.",
        caffeineGramsNotice:
            "La colonne caféine de ce fichier ({column}) est en grammes, mais la caféine est stockée en milligrammes, donc Caféine n'a pas été associée. L'associer enregistrerait 0,18 là où l'étiquette indique 180 mg. Réimporter le même fichier plus tard ne comblera pas ce manque — ces lignes seront déjà enregistrées et seront ignorées comme doublons. Si l'en-tête est mal étiqueté et que les valeurs sont réellement en milligrammes, sélectionne-la ci-dessus ; si elles sont réellement en grammes, multiplie-les par 1000 dans le fichier avant l'import, pas après.",
        alcoholNotice:
            "Ce fichier a une colonne alcool ({column}), mais le suivi de l'alcool est désactivé pour ce compte, donc elle ne sera pas importée. Réimporter le même fichier plus tard ne comblera pas ce manque — ces lignes seront déjà enregistrées et seront ignorées comme doublons. Pour conserver ces données, demande à Claude d'activer le suivi de l'alcool (set_alcohol_tracking) avant l'import.",
        sampleValue: "ex. {sample}",
        sourceAppLabel: "Appli source (facultatif)",
        sourceAppHint:
            "Utilisé pour étiqueter les lignes qui n'ont pas de nom d'aliment propre.",
        previewButton: "Aperçu de l'import",
        chooseAnotherButton: "Choisir un autre fichier",
        previewHeading: "Aperçu",
        mealsToImport: {
            one: "{n} repas à importer",
            other: "{n} repas à importer",
        },
        kcalTotal: "{kcal} kcal au total",
        rowsSkipped: "{n} lignes ignorées",
        batchCount: { one: "{n} lot", other: "{n} lots" },
        datesReadAs: "Dates lues comme {format} ; énergie {conversion}.",
        energyConvertedNote: "converti de kJ en kcal",
        energyReadAsKcal: "lu en kcal",
        badDatesWarning:
            "{n} ligne(s) ont été ignorées car leur date n'a pas pu être lue comme {format}{sample}. Reviens en arrière et choisis le format de date correspondant à ton fichier.",
        badDateSample: " (ex. ligne {line} : {value})",
        noTimeWarning:
            "{n} ligne(s) ont une date mais pas d'heure — elles seront enregistrées à midi.",
        splitDatesCount: {
            one: "{n} date compte",
            other: "{n} dates comptent",
        },
        splitDatesWarning:
            " plus de {max} repas (ex. {date}), l'import a donc dû être réparti sur plusieurs lots. Si cette date contient deux entrées avec exactement le même aliment, le même type de repas et les mêmes macros, l'une d'elles pourrait être ignorée comme doublon plutôt qu'importée.",
        tableLine: "Ligne",
        tableWhen: "Quand",
        tableMeal: "Repas",
        tableFood: "Aliment",
        tableProblem: "Problème",
        noNameFallback: "(pas de nom — sera étiqueté par type de repas)",
        showingRows: "Affichage de {shown} sur {total} lignes",
        checkingRows: "Vérification de {n} lignes…",
        importingRows: "Import de {n} lignes…",
        batchProgress: "{label} (lot {done} sur {total})",
        rowsRange: "Lignes {a}–{b} : {msg}",
        preflightFailed: "La vérification préalable a échoué.",
        rowsWouldFail:
            "{n} ligne(s) échoueraient, ex. ligne {line} : {message}",
        importingEllipsis: "Import en cours…",
        importButton: "Importer {n} repas",
        backToMapping: "Retour à l'association",
        importCompleteHeading: "Import terminé",
        resultMealsImported: "{n} repas importés",
        resultAlreadyLogged: ", {n} déjà enregistrés",
        resultFailed: ", {n} échoués",
        resultSkipped: ", {n} ignorés",
        restartButton: "Importer un autre fichier",
        couldNotReadFile: "Impossible de lire ce fichier : {msg}",
        noDataRows: "Aucune ligne de données trouvée dans ce fichier.",
        emailNotice:
            "Ça ne fonctionne pas comme prévu ? Écris à {email} et inclus les lignes ci-dessous — c'est tout ce qu'il faut pour diagnostiquer le problème.",
    },
};
