import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_ES: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calorías",
            protein_g: "Proteína",
            carbs_g: "Carbos",
            fat_g: "Grasa",
            sugar_g: "Azúcar",
            alcohol_g: "Alcohol",
            caffeine_mg: "Cafeína",
            fiber_g: "Fibra",
            water_ml: "Agua",
        },
        noGoalSet: "sin meta establecida",
        atLimit: "en el límite",
        floorUnder: "restante",
        ceilingUnder: "por debajo",
        over: "de más",
        limitPrefix: "límite",
        ofPrefix: "de",
        drinkLabels: { us: "bebidas EE. UU.", uk: "unidades RU" },
        noneLogged: "nada registrado",
        tapHint: "Toca una métrica para ver las comidas detrás de ella",
        showMealsContributed: "Mostrar las comidas que contribuyeron.",
        byMealTitle: "{label} por comida",
        closeBreakdown: "Cerrar desglose",
        noMealsContributed: "Ninguna comida registrada contribuyó a {label}.",
        untitledMeal: "Comida sin título",
        moreMeals: {
            one: "+ {n} comida más pequeña",
            other: "+ {n} comidas más pequeñas",
        },
    },
    nutritionSummary: {
        title: "Resumen nutricional",
        loading: "Cargando tu resumen nutricional…",
        empty: "No se registraron comidas ni agua en este rango.",
        caloriesPerDay: "Calorías / día",
        avg: "prom.",
        goal: "meta",
        dailyAvgLoggedDays: "Promedio diario · días registrados",
        total: "Total",
        daysLogged: {
            one: "{n} día registrado",
            other: "{n} días registrados",
        },
        daysOfLogged: "{logged} de {span} días registrados",
        months: [
            "ene",
            "feb",
            "mar",
            "abr",
            "may",
            "jun",
            "jul",
            "ago",
            "sep",
            "oct",
            "nov",
            "dic",
        ],
    },
    goalProgress: {
        title: "Progreso de la meta",
        empty: "No hay progreso de meta que mostrar.",
        nothingLoggedFor: "Aún no se ha registrado nada para {date}.",
        thisDay: "este día",
        mealsCount: { one: "{n} comida", other: "{n} comidas" },
        waterCount: { one: "{n} agua", other: "{n} aguas" },
        weightLabel: "Peso",
        weightNoneNoTarget:
            "Aún no se ha registrado ningún peso. Registra uno con log_weight para hacer seguimiento del progreso.",
        weightNoneWithTarget:
            "Aún no se ha registrado ningún peso. Registra uno con log_weight para hacer seguimiento del progreso hacia tu meta de {target}.",
        weightNoGoal:
            "Peso {reading} — sin meta establecida. Establece una con set_nutrition_goals para ver el progreso aquí.",
        atTarget: "en la meta",
        toLose: "{amount} por perder",
        toGain: "{amount} por ganar",
        lastLogged: "último registro {date}",
        weightAria: "Peso {current}, meta {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Comida registrada",
        titleUpdated: "Comida actualizada",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "Tendencias",
        empty: "Aún no se registraron comidas ni agua en este rango.",
        avgUnder: "por debajo",
        loggedOfTotal: "{logged}/{total} días registrados",
        caloriesOverRange: "Calorías por día en los últimos {range} días",
        windowAriaLabel: "Ventana de tendencia",
        rangeDaysAriaLabel: "{n} días",
        avgAllDays: "prom. de {range} días · todos los días",
    },
    weightTrends: {
        title: "Peso",
        empty: "Aún no se registró peso en este rango.",
        rangeEmpty:
            "No hay pesajes en los últimos {range} días. Prueba un rango más amplio.",
        windowAriaLabel: "Ventana de tendencia",
        rangeAriaLabel: "Últimos {n} días",
        chartAriaLabel: "Peso desde {from} hasta {to}, último {latest}",
        latest: "Último",
        needTwo: "se necesitan 2+ pesajes",
        sinceDate: "{change} desde {date}",
        weighIns: { one: "{n} pesaje", other: "{n} pesajes" },
        atTarget: "en la meta",
        toLose: "{amount} por perder",
        toGain: "{amount} por ganar",
        target: "Meta {value}",
        noTarget: "Sin meta establecida",
    },
    importMeals: {
        stepFile: "Archivo",
        stepMap: "Asignar columnas",
        stepPreview: "Vista previa",
        stepImport: "Importar",
        fieldLabels: {
            logged_at: "Fecha / hora",
            description: "Nombre del alimento",
            meal_type: "Comida",
            calories: "Calorías",
            protein_g: "Proteína (g)",
            carbs_g: "Carbohidratos (g)",
            fat_g: "Grasa (g)",
            fiber_g: "Fibra (g)",
            sugar_g: "Azúcar, total (g)",
            alcohol_g: "Alcohol (g)",
            caffeine_mg: "Cafeína (mg)",
            notes: "Notas",
            time: "Hora (columna separada)",
            deleted: "Marca de eliminado",
            source_id: "ID de comida (de nuestra exportación)",
            timezone: "Zona horaria (de nuestra exportación)",
        },
        chooseExportHeading: "Elige tu exportación",
        noToolsWarning:
            "Este host no permite que esta vista escriba en tu registro. Pídele a Claude que importe el archivo en su lugar — puede hacerlo directamente.",
        emailFallback:
            "Si pedírselo a Claude tampoco funciona, escribe a {email}.",
        tzWarning:
            "Tu zona horaria no está establecida, así que las horas se leerán en UTC y podrían caer en el día equivocado. Pídele a Claude que configure tu zona horaria primero.",
        dropChoose: "Elige un archivo CSV",
        dropOr: "o arrástralo aquí",
        recognizedHint:
            "Las exportaciones de MyFitnessPal, Cronometer, Lose It! y MacroFactor se reconocen automáticamente. No se guarda nada hasta que confirmes.",
        dateMapHint:
            "Asigna una columna de fecha arriba para ver cómo se convierte un valor de tu archivo.",
        dateNoneHint: "Esa columna no contiene fechas.",
        dateUnreadable:
            "{raw} → no se puede leer como {format}, así que las filas similares se omitirán",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Asigna una columna de calorías arriba para ver cómo se convierte un valor de tu archivo.",
        energyNoneHint: "Esa columna no contiene números.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (sin conversión)",
        dateAmbiguousWarning:
            "No se pudo determinar el formato de fecha de este archivo — sus fechas se leen igual de bien como día-primero o mes-primero. Confirma cuál exporta tu aplicación: la elección incorrecta registrará las comidas en el día equivocado sin ningún error.",
        dateFormatLabel: "Formato de fecha en este archivo",
        dateFormatYmd: "Año-Mes-Día",
        dateFormatDmy: "Día/Mes/Año",
        dateFormatMdy: "Mes/Día/Año",
        energyUnitLabel: "Unidad de energía de la columna de calorías",
        energyUnitKcal: "Calorías",
        energyUnitKj: "Kilojulios",
        mapColumnsHeading: "Asignar columnas",
        rowsCount: { one: "{n} fila", other: "{n} filas" },
        columnsCount: { one: "{n} columna", other: "{n} columnas" },
        delimiterLabel: "delimitador",
        tabLabel: "tabulación",
        notInFile: "(no está en este archivo)",
        columnFallback: "columna {n}",
        addedSugarNotice:
            "Este archivo tiene una columna de azúcar añadido ({column}) pero no una columna de azúcar total, así que Azúcar se dejó sin asignar. El azúcar se almacena como azúcares TOTALES, incluyendo los que ocurren naturalmente en la fruta y la leche, así que asignar el azúcar añadido subestimaría cada fila.",
        caffeineGramsNotice:
            "La columna de cafeína de este archivo ({column}) está en gramos, pero la cafeína se almacena en miligramos, así que Cafeína se dejó sin asignar. Asignarla registraría 0.18 donde la etiqueta dice 180 mg. Volver a importar el mismo archivo más tarde no lo completará — esas filas ya estarán registradas y se omitirán como duplicadas. Si el encabezado está mal etiquetado y los valores en realidad están en miligramos, selecciónala arriba; si en realidad están en gramos, multiplícalos por 1000 en el archivo antes de importar, no después.",
        alcoholNotice:
            "Este archivo tiene una columna de alcohol ({column}), pero el seguimiento de alcohol está desactivado para esta cuenta, así que no se importará. Volver a importar el mismo archivo más tarde no lo completará — esas filas ya estarán registradas y se omitirán como duplicadas. Para conservar estos datos, pídele a Claude que active el seguimiento de alcohol (set_alcohol_tracking) antes de importar.",
        sampleValue: "p. ej. {sample}",
        sourceAppLabel: "Aplicación de origen (opcional)",
        sourceAppHint:
            "Se usa para etiquetar filas que no tienen nombre de alimento propio.",
        previewButton: "Previsualizar importación",
        chooseAnotherButton: "Elegir otro archivo",
        previewHeading: "Vista previa",
        mealsToImport: {
            one: "{n} comida para importar",
            other: "{n} comidas para importar",
        },
        kcalTotal: "{kcal} kcal en total",
        rowsSkipped: "{n} filas omitidas",
        batchCount: { one: "{n} lote", other: "{n} lotes" },
        datesReadAs: "Fechas leídas como {format}; energía {conversion}.",
        energyConvertedNote: "convertida de kJ a kcal",
        energyReadAsKcal: "leída como kcal",
        badDatesWarning:
            "{n} fila(s) se omitieron porque su fecha no se pudo leer como {format}{sample}. Vuelve atrás y establece el formato de fecha que coincida con tu archivo.",
        badDateSample: " (p. ej. línea {line}: {value})",
        noTimeWarning:
            "{n} fila(s) tienen fecha pero no hora — se registrarán al mediodía.",
        splitDatesCount: {
            one: "{n} fecha tiene",
            other: "{n} fechas tienen",
        },
        splitDatesWarning:
            " más de {max} comidas (p. ej. {date}); fue necesario dividir la importación en varios lotes. Si esa fecha contiene dos entradas con exactamente el mismo alimento, tipo de comida y macros, una de ellas podría omitirse como duplicada en lugar de importarse.",
        tableLine: "Línea",
        tableWhen: "Cuándo",
        tableMeal: "Comida",
        tableFood: "Alimento",
        tableProblem: "Problema",
        noNameFallback: "(sin nombre — se etiquetará por comida)",
        showingRows: "Mostrando {shown} de {total} filas",
        checkingRows: "Comprobando {n} filas…",
        importingRows: "Importando {n} filas…",
        batchProgress: "{label} (lote {done} de {total})",
        rowsRange: "Filas {a}–{b}: {msg}",
        preflightFailed: "La verificación previa falló.",
        rowsWouldFail: "{n} fila(s) fallarían, p. ej. línea {line}: {message}",
        importingEllipsis: "Importando…",
        importButton: "Importar {n} comidas",
        backToMapping: "Volver a la asignación",
        importCompleteHeading: "Importación completa",
        resultMealsImported: "{n} comidas importadas",
        resultAlreadyLogged: ", {n} ya registradas",
        resultFailed: ", {n} fallidas",
        resultSkipped: ", {n} omitidas",
        restartButton: "Importar otro archivo",
        couldNotReadFile: "No se pudo leer ese archivo: {msg}",
        noDataRows: "No se encontraron filas de datos en ese archivo.",
        emailNotice:
            "¿No funciona como se esperaba? Escribe a {email} e incluye las líneas de abajo — eso es todo lo necesario para diagnosticarlo.",
    },
};
