import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_UK: WidgetStrings = {
    macros: {
        labels: {
            calories: "Калорії",
            protein_g: "Білки",
            carbs_g: "Вуглеводи",
            fat_g: "Жири",
            sugar_g: "Цукор",
            alcohol_g: "Алкоголь",
            caffeine_mg: "Кофеїн",
            fiber_g: "Клітковина",
            water_ml: "Вода",
        },
        noGoalSet: "ціль не задана",
        atLimit: "на межі",
        floorUnder: "залишилось",
        ceilingUnder: "до ліміту",
        over: "перевищено",
        limitPrefix: "ліміт",
        ofPrefix: "з",
        drinkLabels: { us: "порції США", uk: "од. Великобританії" },
        noneLogged: "немає записів",
        tapHint: "Торкніться показника, щоб побачити страви",
        showMealsContributed: "Показати страви, що це склали.",
        byMealTitle: "{label} за стравами",
        closeBreakdown: "Закрити деталізацію",
        noMealsContributed: "Жодна із зареєстрованих страв не містить {label}.",
        untitledMeal: "Страва без назви",
        moreMeals: {
            one: "+ ще {n} менша страва",
            other: "+ ще {n} менших страв",
        },
    },
    nutritionSummary: {
        title: "Підсумок харчування",
        loading: "Завантаження підсумку харчування…",
        empty: "За цей період немає записів про страви чи воду.",
        caloriesPerDay: "Калорії / день",
        avg: "сер.",
        goal: "ціль",
        dailyAvgLoggedDays: "Середнє за день · дні з записами",
        total: "Всього",
        daysLogged: {
            one: "{n} день з записом",
            other: "{n} днів з записами",
        },
        daysOfLogged: "{logged} із {span} днів з записами",
        months: [
            "Січ",
            "Лют",
            "Бер",
            "Кві",
            "Тра",
            "Чер",
            "Лип",
            "Сер",
            "Вер",
            "Жов",
            "Лис",
            "Гру",
        ],
    },
    goalProgress: {
        title: "Прогрес цілі",
        empty: "Немає прогресу цілі для показу.",
        nothingLoggedFor: "За {date} ще немає записів.",
        thisDay: "цей день",
        mealsCount: { one: "{n} страва", other: "{n} страв" },
        waterCount: { one: "{n} запис води", other: "{n} записів води" },
        weightLabel: "Вага",
        weightNoneNoTarget:
            "Вага ще не записана. Запиши її за допомогою log_weight, щоб відстежувати прогрес.",
        weightNoneWithTarget:
            "Вага ще не записана. Запиши її за допомогою log_weight, щоб відстежувати прогрес до цілі {target}.",
        weightNoGoal:
            "Вага {reading} — ціль не задана. Задай її за допомогою set_nutrition_goals, щоб бачити тут прогрес.",
        atTarget: "на цілі",
        toLose: "лишилось скинути {amount}",
        toGain: "лишилось набрати {amount}",
        lastLogged: "востаннє записано {date}",
        weightAria: "Вага {current}, ціль {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Страву записано",
        titleUpdated: "Страву оновлено",
        addedKcal: "+{kcal} ккал",
    },
    trends: {
        title: "Тренди",
        empty: "За цей період ще немає записів про страви чи воду.",
        avgUnder: "нижче",
        loggedOfTotal: "{logged}/{total} днів з записами",
        caloriesOverRange: "Калорії за день за останні {range} днів",
        windowAriaLabel: "Період тренду",
        rangeDaysAriaLabel: "{n} днів",
        avgAllDays: "Сер. за {range} дн. · всі дні",
    },
    weightTrends: {
        title: "Вага",
        empty: "За цей період ще немає записів ваги.",
        rangeEmpty:
            "Немає зважувань за останні {range} днів. Спробуй ширший період.",
        windowAriaLabel: "Період тренду",
        rangeAriaLabel: "Останні {n} днів",
        chartAriaLabel: "Вага з {from} по {to}, останнє значення {latest}",
        latest: "Останнє",
        needTwo: "потрібно 2+ зважування",
        sinceDate: "{change} з {date}",
        weighIns: { one: "{n} зважування", other: "{n} зважувань" },
        atTarget: "на цілі",
        toLose: "лишилось скинути {amount}",
        toGain: "лишилось набрати {amount}",
        target: "Ціль {value}",
        noTarget: "Ціль не задана",
    },
    importMeals: {
        stepFile: "Файл",
        stepMap: "Зіставлення колонок",
        stepPreview: "Перегляд",
        stepImport: "Імпорт",
        fieldLabels: {
            logged_at: "Дата / час",
            description: "Назва страви",
            meal_type: "Прийом їжі",
            calories: "Калорії",
            protein_g: "Білки (г)",
            carbs_g: "Вуглеводи (г)",
            fat_g: "Жири (г)",
            fiber_g: "Клітковина (г)",
            sugar_g: "Цукор, загальний (г)",
            alcohol_g: "Алкоголь (г)",
            caffeine_mg: "Кофеїн (мг)",
            notes: "Примітки",
            time: "Час (окрема колонка)",
            deleted: "Позначка видалення",
            source_id: "ID страви (з нашого експорту)",
            timezone: "Часовий пояс (з нашого експорту)",
        },
        chooseExportHeading: "Вибери свій експорт",
        noToolsWarning:
            "Цей застосунок не дозволяє цьому вікну записувати дані в твій журнал. Попроси ШІ імпортувати файл замість цього — він може зробити це напряму.",
        emailFallback:
            "Якщо звернення до ШІ також не допоможе, напиши на {email}.",
        tzWarning:
            "Твій часовий пояс не встановлено, тому час буде зчитуватися як UTC і може потрапити не на той день. Спершу попроси ШІ встановити твій часовий пояс.",
        dropChoose: "Обери CSV-файл",
        dropOr: "або перетягни його сюди",
        recognizedHint:
            "Експорти з MyFitnessPal, Cronometer, Lose It! та MacroFactor розпізнаються автоматично. Нічого не зберігається, доки ти не підтвердиш.",
        dateMapHint:
            "Зістав колонку з датою вище, щоб побачити, як конвертується значення з твого файлу.",
        dateNoneHint: "У цій колонці немає дат.",
        dateUnreadable:
            "{raw} → не вдається прочитати як {format}, тому такі рядки буде пропущено",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Зістав колонку з калоріями вище, щоб побачити, як конвертується значення з твого файлу.",
        energyNoneHint: "У цій колонці немає чисел.",
        energyConverted: "{v} кДж → {kcal} ккал",
        energyNoConversion: "{v} ккал → {v} ккал (без конвертації)",
        dateAmbiguousWarning:
            "Формат дати не вдалося визначити з цього файлу — дати однаково добре читаються і як день-перший, і як місяць-перший. Підтверди, який формат використовує твій застосунок: неправильний вибір запише прийоми їжі не на той день без жодної помилки.",
        dateFormatLabel: "Формат дати в цьому файлі",
        dateFormatYmd: "Рік-Місяць-День",
        dateFormatDmy: "День/Місяць/Рік",
        dateFormatMdy: "Місяць/День/Рік",
        energyUnitLabel: "Одиниця енергії в колонці калорій",
        energyUnitKcal: "Калорії",
        energyUnitKj: "Кілоджоулі",
        mapColumnsHeading: "Зіставлення колонок",
        rowsCount: { one: "{n} рядок", other: "{n} рядків" },
        columnsCount: { one: "{n} колонка", other: "{n} колонок" },
        delimiterLabel: "роздільник",
        tabLabel: "табуляція",
        notInFile: "(немає в цьому файлі)",
        columnFallback: "колонка {n}",
        addedSugarNotice:
            "У цьому файлі є колонка доданого цукру ({column}), але немає колонки загального цукру, тож поле «Цукор» залишено незіставленим. Цукор зберігається як ЗАГАЛЬНИЙ цукор, включно з тим, що природно міститься у фруктах і молоці, тому зіставлення доданого цукру з ним занизило б показник у кожному рядку.",
        caffeineGramsNotice:
            "Колонка кофеїну в цьому файлі ({column}) вказана в грамах, але кофеїн зберігається в міліграмах, тож поле «Кофеїн» залишено незіставленим. Зіставлення записало б 0.18 там, де на етикетці вказано 180 мг. Повторний імпорт цього ж файлу пізніше не заповнить це поле — ці рядки вже буде записано, і вони будуть пропущені як дублікати. Якщо заголовок вказано неправильно і значення насправді в міліграмах, обери цю колонку вище; якщо вони справді в грамах, помнож їх на 1000 у файлі перед імпортом, а не після.",
        alcoholNotice:
            "У цьому файлі є колонка алкоголю ({column}), але відстеження алкоголю вимкнено для цього акаунту, тож її не буде імпортовано. Повторний імпорт цього ж файлу пізніше не заповнить це поле — ці рядки вже буде записано, і вони будуть пропущені як дублікати. Щоб зберегти ці дані, попроси ШІ увімкнути відстеження алкоголю (set_alcohol_tracking) перед імпортом.",
        sampleValue: "напр. {sample}",
        sourceAppLabel: "Застосунок-джерело (необов'язково)",
        sourceAppHint:
            "Використовується для позначення рядків, що не мають власної назви страви.",
        previewButton: "Переглянути імпорт",
        chooseAnotherButton: "Обрати інший файл",
        previewHeading: "Перегляд",
        mealsToImport: {
            one: "{n} страва для імпорту",
            other: "{n} страв для імпорту",
        },
        kcalTotal: "{kcal} ккал загалом",
        rowsSkipped: "{n} рядків пропущено",
        batchCount: { one: "{n} пакет", other: "{n} пакетів" },
        datesReadAs: "Дати зчитуються як {format}; енергія {conversion}.",
        energyConvertedNote: "конвертовано з кДж у ккал",
        energyReadAsKcal: "зчитується як ккал",
        badDatesWarning:
            "{n} рядок(-ів) пропущено, оскільки їхню дату не вдалося прочитати як {format}{sample}. Поверніся назад і встанови формат дати, що відповідає твоєму файлу.",
        badDateSample: " (напр. рядок {line}: {value})",
        noTimeWarning:
            "{n} рядок(-ів) мають дату, але без часу — їх буде записано опівдні.",
        splitDatesCount: {
            one: "{n} дата має",
            other: "{n} дат мають",
        },
        splitDatesWarning:
            " понад {max} страв (напр. {date}) і довелося розділити на окремі пакети імпорту. Якщо в цю дату є два записи з однаковою стравою, типом прийому їжі та макронутрієнтами, один із них може бути пропущений як дублікат замість імпортованого.",
        tableLine: "Рядок",
        tableWhen: "Коли",
        tableMeal: "Прийом їжі",
        tableFood: "Страва",
        tableProblem: "Проблема",
        noNameFallback: "(без назви — буде позначено за прийомом їжі)",
        showingRows: "Показано {shown} з {total} рядків",
        checkingRows: "Перевірка {n} рядків…",
        importingRows: "Імпортування {n} рядків…",
        batchProgress: "{label} (пакет {done} з {total})",
        rowsRange: "Рядки {a}–{b}: {msg}",
        preflightFailed: "Попередня перевірка не пройшла.",
        rowsWouldFail:
            "{n} рядок(-ів) не пройдуть, напр. рядок {line}: {message}",
        importingEllipsis: "Імпортування…",
        importButton: "Імпортувати {n} страв",
        backToMapping: "Назад до зіставлення",
        importCompleteHeading: "Імпорт завершено",
        resultMealsImported: "{n} страв імпортовано",
        resultAlreadyLogged: ", {n} вже записано",
        resultFailed: ", {n} з помилками",
        resultSkipped: ", {n} пропущено",
        restartButton: "Імпортувати інший файл",
        couldNotReadFile: "Не вдалося прочитати файл: {msg}",
        noDataRows: "У файлі не знайдено рядків з даними.",
        emailNotice:
            "Щось працює не так? Напиши на {email} і додай рядки нижче — цього достатньо, щоб усе діагностувати.",
    },
};
