import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_NL: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calorieën",
            protein_g: "Eiwitten",
            carbs_g: "Koolhydraten",
            fat_g: "Vet",
            sugar_g: "Suiker",
            alcohol_g: "Alcohol",
            caffeine_mg: "Cafeïne",
            fiber_g: "Vezels",
            water_ml: "Water",
        },
        noGoalSet: "geen doel ingesteld",
        atLimit: "op de limiet",
        floorUnder: "te gaan",
        ceilingUnder: "onder",
        over: "te veel",
        limitPrefix: "limiet",
        ofPrefix: "van",
        drinkLabels: { us: "VS-drankjes", uk: "VK-eenheden" },
        units: {
            kcal: "kcal",
            g: "g",
            mg: "mg",
            ml: "ml",
            L: "L",
            kg: "kg",
            lb: "lb",
        },
        noneLogged: "niets gelogd",
        caloriesToday: "Calorieën vandaag",
        caloriesOn: "Calorieën · {date}",
        tapHint: "Tik op een waarde voor de bijbehorende maaltijden",
        showMealsContributed: "Toon de maaltijden die hieraan bijdroegen.",
        byMealTitle: "{label} per maaltijd",
        closeBreakdown: "Overzicht sluiten",
        noMealsContributed: "Geen gelogde maaltijden droegen bij aan {label}.",
        untitledMeal: "Naamloze maaltijd",
        moreMeals: {
            one: "+ {n} kleinere maaltijd",
            other: "+ {n} kleinere maaltijden",
        },
        moreMealsAtLeast: {
            one: "+ {n} of meer kleinere maaltijden",
            other: "+ {n} of meer kleinere maaltijden",
        },
        moreMealsMaybe: "+ mogelijk meer kleinere maaltijden",
    },
    bridge: {
        settingsFooter:
            "Je kunt deze widgets altijd in- of uitschakelen — vraag gewoon om je instellingen aan te passen.",
        connectFailed: "Deze weergave kon geen verbinding maken met de host.",
    },
    nutritionSummary: {
        title: "Voedingsoverzicht",
        loading: "Je voedingsoverzicht wordt geladen…",
        empty: "Geen maaltijden of water gelogd in deze periode.",
        caloriesPerDay: "Calorieën / dag",
        chartAriaLabel: "Calorieën per dag in de geselecteerde periode",
        avg: "gem.",
        goal: "doel",
        dailyAvgLoggedDays: "Dagelijks gem. · gelogde dagen",
        total: "Totaal",
        daysLogged: {
            one: "{n} dag gelogd",
            other: "{n} dagen gelogd",
        },
        daysOfLogged: "{logged} van {span} dagen gelogd",
        months: [
            "Jan",
            "Feb",
            "Mrt",
            "Apr",
            "Mei",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Okt",
            "Nov",
            "Dec",
        ],
    },
    goalProgress: {
        loading: "Je doelvoortgang wordt geladen…",
        title: "Doelvoortgang",
        empty: "Geen doelvoortgang om te tonen.",
        nothingLoggedFor: "Nog niets gelogd voor {date}.",
        thisDay: "deze dag",
        mealsCount: { one: "{n} maaltijd", other: "{n} maaltijden" },
        waterCount: { one: "{n} keer water", other: "{n} keer water" },
        weightLabel: "Gewicht",
        weightNoneNoTarget:
            "Nog geen gewicht gelogd. Log er een met log_weight om je voortgang bij te houden.",
        weightNoneWithTarget:
            "Nog geen gewicht gelogd. Log er een met log_weight om je voortgang naar je streefgewicht van {target} bij te houden.",
        weightNoGoal:
            "Gewicht {reading} — geen doel ingesteld. Stel er een in met set_nutrition_goals om hier je voortgang te zien.",
        atTarget: "op doelgewicht",
        toLose: "{amount} af te vallen",
        toGain: "{amount} aan te komen",
        lastLogged: "laatst gelogd op {date}",
        weightAria: "Gewicht {current}, doel {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Maaltijd gelogd",
        titleUpdated: "Maaltijd bijgewerkt",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        loading: "Je trends worden geladen…",
        title: "Trends",
        empty: "Nog geen maaltijden of water gelogd in deze periode.",
        avgUnder: "onder",
        loggedOfTotal: "{logged}/{total} dagen gelogd",
        caloriesOverRange: "Calorieën per dag over de afgelopen {range} dagen",
        windowAriaLabel: "Trendperiode",
        rangeDaysAriaLabel: "{n} dagen",
        avgAllDays: "{range}-daags gem. · alle dagen",
    },
    weightTrends: {
        loading: "Je gewichtsverloop wordt geladen…",
        title: "Gewicht",
        empty: "Nog geen gewicht gelogd in deze periode.",
        rangeEmpty:
            "Geen weegmomenten in de afgelopen {range} dagen. Probeer een langere periode.",
        windowAriaLabel: "Trendperiode",
        rangeAriaLabel: "Laatste {n} dagen",
        chartAriaLabel: "Gewicht van {from} tot {to}, laatste {latest}",
        latest: "Laatste",
        needTwo: "minstens 2 weegmomenten nodig",
        sinceDate: "{change} sinds {date}",
        weighIns: { one: "{n} weegmoment", other: "{n} weegmomenten" },
        atTarget: "op doelgewicht",
        toLose: "{amount} af te vallen",
        toGain: "{amount} aan te komen",
        target: "Doel {value}",
        noTarget: "Geen doel ingesteld",
    },
    importMeals: {
        loading: "Import wordt voorbereid…",
        stepFile: "Bestand",
        stepMap: "Kolommen koppelen",
        stepPreview: "Voorbeeld",
        stepImport: "Importeren",
        fieldLabels: {
            logged_at: "Datum / tijd",
            description: "Naam voedingsmiddel",
            meal_type: "Maaltijd",
            calories: "Calorieën",
            protein_g: "Eiwitten (g)",
            carbs_g: "Koolhydraten (g)",
            fat_g: "Vet (g)",
            fiber_g: "Vezels (g)",
            sugar_g: "Suiker, totaal (g)",
            alcohol_g: "Alcohol (g)",
            caffeine_mg: "Cafeïne (mg)",
            notes: "Notities",
            time: "Tijd (aparte kolom)",
            deleted: "Verwijderd-markering",
            source_id: "Maaltijd-id (uit onze export)",
            timezone: "Tijdzone (uit onze export)",
        },
        chooseExportHeading: "Kies je export",
        noToolsWarning:
            "Deze host staat dit venster niet toe om in je logboek te schrijven. Vraag Claude om het bestand in plaats daarvan te importeren — dat kan Claude rechtstreeks doen.",
        emailFallback:
            "Werkt het vragen van Claude ook niet? Mail dan naar {email}.",
        tzWarning:
            "Je tijdzone is niet ingesteld, dus tijden worden als UTC gelezen en kunnen op de verkeerde dag terechtkomen. Vraag Claude om eerst je tijdzone in te stellen.",
        dropChoose: "Kies een CSV-bestand",
        dropOr: "of sleep het hierheen",
        recognizedHint:
            "Exports van MyFitnessPal, Cronometer, Lose It! en MacroFactor worden automatisch herkend. Er wordt niets opgeslagen totdat je bevestigt.",
        dateMapHint:
            "Koppel hierboven een datumkolom om te zien hoe een waarde uit je bestand wordt omgezet.",
        dateNoneHint: "Die kolom bevat geen datums.",
        dateUnreadable:
            "{raw} → kan niet worden gelezen als {format}, dus rijen zoals deze worden overgeslagen",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Koppel hierboven een calorieënkolom om te zien hoe een waarde uit je bestand wordt omgezet.",
        energyNoneHint: "Die kolom bevat geen getallen.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (geen omrekening)",
        dateAmbiguousWarning:
            "Het datumformaat kon niet worden bepaald uit dit bestand — de datums zijn zowel als dag-eerst als maand-eerst te lezen. Bevestig welk formaat jouw app exporteert: bij de verkeerde keuze worden maaltijden zonder foutmelding op de verkeerde dag gelogd.",
        dateFormatLabel: "Datumformaat in dit bestand",
        dateFormatYmd: "Jaar-Maand-Dag",
        dateFormatDmy: "Dag/Maand/Jaar",
        dateFormatMdy: "Maand/Dag/Jaar",
        energyUnitLabel: "Energie-eenheid van de calorieënkolom",
        energyUnitKcal: "Calorieën",
        energyUnitKj: "Kilojoules",
        mapColumnsHeading: "Kolommen koppelen",
        rowsCount: { one: "{n} rij", other: "{n} rijen" },
        columnsCount: { one: "{n} kolom", other: "{n} kolommen" },
        delimiterLabel: "scheidingsteken",
        tabLabel: "tab",
        notInFile: "(niet in dit bestand)",
        columnFallback: "kolom {n}",
        addedSugarNotice:
            "Dit bestand heeft een kolom voor toegevoegde suikers ({column}), maar geen kolom voor totale suikers, dus Suiker is niet gekoppeld. Suiker wordt opgeslagen als TOTALE suikers, inclusief wat van nature in fruit en melk voorkomt, dus het koppelen van toegevoegde suikers hieraan zou elke rij te laag weergeven.",
        caffeineGramsNotice:
            "De cafeïnekolom van dit bestand ({column}) staat in gram, maar cafeïne wordt hier opgeslagen in milligram, dus Cafeïne is niet gekoppeld. Koppelen zou 0,18 vastleggen waar het label 180 mg zegt. Dit bestand later opnieuw importeren vult dit niet alsnog aan — die rijen zijn dan al gelogd en worden als duplicaten overgeslagen. Als de kolomkop verkeerd is benoemd en de waarden echt in milligram zijn, kies de kolom dan hierboven; zijn ze echt in gram, vermenigvuldig ze dan in het bestand met 1000 vóór het importeren, niet erna.",
        alcoholNotice:
            "Dit bestand heeft een alcoholkolom ({column}), maar alcoholregistratie staat uit voor dit account, dus deze wordt niet geïmporteerd. Dit bestand later opnieuw importeren vult dit niet alsnog aan — die rijen zijn dan al gelogd en worden als duplicaten overgeslagen. Vraag Claude om alcoholregistratie (set_alcohol_tracking) in te schakelen vóór het importeren als je deze gegevens wilt behouden.",
        sampleValue: "bijv. {sample}",
        sourceAppLabel: "Bron-app (optioneel)",
        sourceAppHint:
            "Wordt gebruikt om rijen zonder eigen voedingsmiddelnaam te labelen.",
        previewButton: "Voorbeeld van import",
        chooseAnotherButton: "Kies een ander bestand",
        previewHeading: "Voorbeeld",
        mealsToImport: {
            one: "{n} maaltijd om te importeren",
            other: "{n} maaltijden om te importeren",
        },
        kcalTotal: "{kcal} kcal totaal",
        rowsSkipped: {
            one: "{n} rij overgeslagen",
            other: "{n} rijen overgeslagen",
        },
        batchCount: { one: "{n} batch", other: "{n} batches" },
        datesReadAs: "Datums gelezen als {format}; energie {conversion}.",
        energyConvertedNote: "omgerekend van kJ naar kcal",
        energyReadAsKcal: "gelezen als kcal",
        badDatesWarning: {
            one: "{n} rij is overgeslagen omdat de datum niet als {format} kon worden gelezen{sample}. Ga terug en stel het datumformaat in dat bij je bestand past.",
            other: "{n} rijen zijn overgeslagen omdat de datum niet als {format} kon worden gelezen{sample}. Ga terug en stel het datumformaat in dat bij je bestand past.",
        },
        badDateSample: " (bijv. regel {line}: {value})",
        noTimeWarning: {
            one: "{n} rij heeft een datum maar geen tijd — deze wordt op het middaguur gelogd.",
            other: "{n} rijen hebben een datum maar geen tijd — deze worden op het middaguur gelogd.",
        },
        splitDatesCount: {
            one: "{n} datum heeft",
            other: "{n} datums hebben",
        },
        splitDatesWarning:
            " meer dan {max} maaltijden (bijv. {date}); de import moest daarom worden opgesplitst over meerdere importbatches. Als die datum twee items bevat met exact hetzelfde voedingsmiddel, dezelfde maaltijdsoort en dezelfde macro's, kan een van beide als duplicaat worden overgeslagen in plaats van geïmporteerd.",
        tableAbbr: {
            protein_g: "E",
            carbs_g: "K",
            fat_g: "V",
            fiber_g: "Vezels",
            sugar_g: "Suiker",
            alcohol_g: "Alc",
            caffeine_mg: "Caf",
        },
        tableLine: "Regel",
        tableWhen: "Wanneer",
        tableMeal: "Maaltijd",
        tableFood: "Voedingsmiddel",
        tableProblem: "Probleem",
        noNameFallback: "(geen naam — wordt benoemd naar maaltijd)",
        showingRows: "{shown} van {total} rijen weergegeven",
        checkingRows: {
            one: "{n} rij wordt gecontroleerd…",
            other: "{n} rijen worden gecontroleerd…",
        },
        importingRows: {
            one: "{n} rij wordt geïmporteerd…",
            other: "{n} rijen worden geïmporteerd…",
        },
        batchProgress: "{label} (batch {done} van {total})",
        rowsRange: "Rijen {a}–{b}: {msg}",
        preflightFailed: "Voorafcontrole mislukt.",
        rowsWouldFail: {
            one: "{n} rij zou mislukken, bijv. regel {line}: {message}",
            other: "{n} rijen zouden mislukken, bijv. regel {line}: {message}",
        },
        importingEllipsis: "Bezig met importeren…",
        importButton: {
            one: "{n} maaltijd importeren",
            other: "{n} maaltijden importeren",
        },
        backToMapping: "Terug naar koppelen",
        importCompleteHeading: "Import voltooid",
        resultMealsImported: {
            one: "{n} maaltijd geïmporteerd",
            other: "{n} maaltijden geïmporteerd",
        },
        resultAlreadyLogged: {
            one: ", {n} al gelogd",
            other: ", {n} al gelogd",
        },
        resultFailed: {
            one: ", {n} mislukt",
            other: ", {n} mislukt",
        },
        resultSkipped: {
            one: ", {n} overgeslagen",
            other: ", {n} overgeslagen",
        },
        restartButton: "Nog een bestand importeren",
        couldNotReadFile: "Kon dat bestand niet lezen: {msg}",
        noDataRows: "Geen datarijen gevonden in dat bestand.",
        emailNotice:
            "Werkt het niet zoals verwacht? Mail naar {email} en voeg de onderstaande regels toe — dat is alles wat nodig is om het te diagnosticeren.",
    },
};
