import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_ES: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calorías",
            protein_g: "Proteína",
            carbs_g: "Carbos",
            fat_g: "Grasa",
            sugar_g: "Azúcar",
            alcohol_g: "Alcohol",
            caffeine_mg: "Cafeína",
            fiber_g: "Fibra",
            water_ml: "Agua",
        },
        noGoalSet: "sin meta establecida",
        atLimit: "en el límite",
        floorUnder: "restante",
        ceilingUnder: "por debajo",
        over: "de más",
        limitPrefix: "límite",
        ofPrefix: "de",
        drinkLabels: { us: "bebidas EE. UU.", uk: "unidades RU" },
        noneLogged: "nada registrado",
        tapHint: "Toca una métrica para ver las comidas detrás de ella",
        showMealsContributed: "Mostrar las comidas que contribuyeron.",
        byMealTitle: "{label} por comida",
        closeBreakdown: "Cerrar desglose",
        noMealsContributed: "Ninguna comida registrada contribuyó a {label}.",
        untitledMeal: "Comida sin título",
        moreMeals: {
            one: "+ {n} comida más pequeña",
            other: "+ {n} comidas más pequeñas",
        },
    },
    nutritionSummary: {
        title: "Resumen nutricional",
        loading: "Cargando tu resumen nutricional…",
        empty: "No se registraron comidas ni agua en este rango.",
        caloriesPerDay: "Calorías / día",
        avg: "prom.",
        goal: "meta",
        dailyAvgLoggedDays: "Promedio diario · días registrados",
        total: "Total",
        daysLogged: {
            one: "{n} día registrado",
            other: "{n} días registrados",
        },
        daysOfLogged: "{logged} de {span} días registrados",
        months: [
            "ene",
            "feb",
            "mar",
            "abr",
            "may",
            "jun",
            "jul",
            "ago",
            "sep",
            "oct",
            "nov",
            "dic",
        ],
    },
};
