import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_DE: WidgetStrings = {
    macros: {
        labels: {
            calories: "Kalorien",
            protein_g: "Eiweiß",
            // Not the full "Kohlenhydrate": it truncates in the compact
            // three-column macro tile (visually confirmed against the
            // assembled widget) the way "Eiweiß"/"Fett" don't.
            carbs_g: "Kohlenh.",
            fat_g: "Fett",
            sugar_g: "Zucker",
            alcohol_g: "Alkohol",
            caffeine_mg: "Koffein",
            fiber_g: "Ballaststoffe",
            water_ml: "Wasser",
        },
        noGoalSet: "kein Ziel festgelegt",
        atLimit: "am Limit",
        floorUnder: "übrig",
        ceilingUnder: "unter",
        over: "über",
        limitPrefix: "Limit",
        ofPrefix: "von",
        drinkLabels: { us: "US-Drinks", uk: "UK-Einheiten" },
        noneLogged: "nichts protokolliert",
        tapHint: "Für die zugehörigen Mahlzeiten auf einen Wert tippen",
        showMealsContributed:
            "Zeigt die Mahlzeiten, die dazu beigetragen haben.",
        byMealTitle: "{label} nach Mahlzeit",
        closeBreakdown: "Aufschlüsselung schließen",
        noMealsContributed:
            "Keine protokollierten Mahlzeiten haben zu {label} beigetragen.",
        untitledMeal: "Unbenannte Mahlzeit",
        moreMeals: {
            one: "+ {n} kleinere Mahlzeit",
            other: "+ {n} kleinere Mahlzeiten",
        },
    },
    nutritionSummary: {
        title: "Ernährungsübersicht",
        loading: "Ernährungsübersicht wird geladen…",
        empty: "In diesem Zeitraum wurden keine Mahlzeiten oder kein Wasser protokolliert.",
        caloriesPerDay: "Kalorien / Tag",
        avg: "Ø",
        goal: "Ziel",
        dailyAvgLoggedDays: "Tagesdurchschnitt · protokollierte Tage",
        total: "Gesamt",
        daysLogged: {
            one: "{n} Tag protokolliert",
            other: "{n} Tage protokolliert",
        },
        daysOfLogged: "{logged} von {span} Tagen protokolliert",
        months: [
            "Jan",
            "Feb",
            "Mär",
            "Apr",
            "Mai",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Okt",
            "Nov",
            "Dez",
        ],
    },
    goalProgress: {
        title: "Zielfortschritt",
        empty: "Kein Zielfortschritt anzuzeigen.",
        nothingLoggedFor: "Für {date} noch nichts protokolliert.",
        thisDay: "diesen Tag",
        mealsCount: { one: "{n} Mahlzeit", other: "{n} Mahlzeiten" },
        waterCount: { one: "{n} Wasser", other: "{n} Wasser" },
        weightLabel: "Gewicht",
        weightNoneNoTarget:
            "Noch kein Gewicht protokolliert. Protokolliere eins mit log_weight, um den Fortschritt zu verfolgen.",
        weightNoneWithTarget:
            "Noch kein Gewicht protokolliert. Protokolliere eins mit log_weight, um den Fortschritt zu deinem Ziel von {target} zu verfolgen.",
        weightNoGoal:
            "Gewicht {reading} — kein Ziel festgelegt. Leg eins mit set_nutrition_goals fest, um hier den Fortschritt zu sehen.",
        atTarget: "am Ziel",
        toLose: "{amount} bis zum Ziel (abnehmen)",
        toGain: "{amount} bis zum Ziel (zunehmen)",
        lastLogged: "zuletzt protokolliert am {date}",
        weightAria: "Gewicht {current}, Ziel {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Mahlzeit protokolliert",
        titleUpdated: "Mahlzeit aktualisiert",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "Trends",
        empty: "In diesem Zeitraum wurden noch keine Mahlzeiten oder kein Wasser protokolliert.",
        avgUnder: "unter",
        loggedOfTotal: "{logged}/{total} Tage protokolliert",
        caloriesOverRange: "Kalorien pro Tag in den letzten {range} Tagen",
        windowAriaLabel: "Trendzeitraum",
        rangeDaysAriaLabel: "{n} Tage",
        avgAllDays: "{range}-Tage-Ø · alle Tage",
    },
    weightTrends: {
        title: "Gewicht",
        empty: "In diesem Zeitraum wurde noch kein Gewicht protokolliert.",
        rangeEmpty:
            "Keine Wiegungen in den letzten {range} Tagen. Versuch einen größeren Zeitraum.",
        windowAriaLabel: "Trendzeitraum",
        rangeAriaLabel: "Letzte {n} Tage",
        chartAriaLabel: "Gewicht von {from} bis {to}, zuletzt {latest}",
        latest: "Zuletzt",
        needTwo: "mindestens 2 Wiegungen nötig",
        sinceDate: "{change} seit {date}",
        weighIns: { one: "{n} Wiegung", other: "{n} Wiegungen" },
        atTarget: "am Ziel",
        toLose: "{amount} bis zum Ziel (abnehmen)",
        toGain: "{amount} bis zum Ziel (zunehmen)",
        target: "Ziel {value}",
        noTarget: "Kein Ziel festgelegt",
    },
    importMeals: {
        stepFile: "Datei",
        stepMap: "Spalten zuordnen",
        stepPreview: "Vorschau",
        stepImport: "Import",
        fieldLabels: {
            logged_at: "Datum / Uhrzeit",
            description: "Name des Lebensmittels",
            meal_type: "Mahlzeit",
            calories: "Kalorien",
            protein_g: "Eiweiß (g)",
            carbs_g: "Kohlenhydrate (g)",
            fat_g: "Fett (g)",
            fiber_g: "Ballaststoffe (g)",
            sugar_g: "Zucker, gesamt (g)",
            alcohol_g: "Alkohol (g)",
            caffeine_mg: "Koffein (mg)",
            notes: "Notizen",
            time: "Uhrzeit (eigene Spalte)",
            deleted: "Gelöscht-Kennzeichen",
            source_id: "Mahlzeit-ID (aus unserem Export)",
            timezone: "Zeitzone (aus unserem Export)",
        },
        chooseExportHeading: "Wähle deinen Export",
        noToolsWarning:
            "Dieser Host erlaubt dieser Ansicht nicht, in dein Protokoll zu schreiben. Bitte Claude, die Datei stattdessen zu importieren — das kann Claude direkt erledigen.",
        emailFallback:
            "Falls auch das Bitten von Claude nicht funktioniert, schreib an {email}.",
        tzWarning:
            "Deine Zeitzone ist nicht festgelegt, daher werden Uhrzeiten als UTC gelesen und können auf den falschen Tag fallen. Bitte Claude, zuerst deine Zeitzone festzulegen.",
        dropChoose: "CSV-Datei auswählen",
        dropOr: "oder hierher ziehen",
        recognizedHint:
            "Exporte von MyFitnessPal, Cronometer, Lose It! und MacroFactor werden automatisch erkannt. Es wird nichts gespeichert, bevor du bestätigst.",
        dateMapHint:
            "Ordne oben eine Datumsspalte zu, um zu sehen, wie ein Wert aus deiner Datei umgewandelt wird.",
        dateNoneHint: "Diese Spalte enthält keine Datumswerte.",
        dateUnreadable:
            "{raw} → kann nicht als {format} gelesen werden, solche Zeilen werden übersprungen",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Ordne oben eine Kalorienspalte zu, um zu sehen, wie ein Wert aus deiner Datei umgewandelt wird.",
        energyNoneHint: "Diese Spalte enthält keine Zahlen.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (keine Umrechnung)",
        dateAmbiguousWarning:
            "Das Datumsformat konnte aus dieser Datei nicht bestimmt werden — die Datumswerte lassen sich sowohl tag- als auch monatsführend lesen. Bitte bestätige, welches Format deine App exportiert: die falsche Wahl protokolliert Mahlzeiten am falschen Tag, ohne einen Fehler anzuzeigen.",
        dateFormatLabel: "Datumsformat in dieser Datei",
        dateFormatYmd: "Jahr-Monat-Tag",
        dateFormatDmy: "Tag/Monat/Jahr",
        dateFormatMdy: "Monat/Tag/Jahr",
        energyUnitLabel: "Energieeinheit der Kalorienspalte",
        energyUnitKcal: "Kalorien",
        energyUnitKj: "Kilojoule",
        mapColumnsHeading: "Spalten zuordnen",
        rowsCount: { one: "{n} Zeile", other: "{n} Zeilen" },
        columnsCount: { one: "{n} Spalte", other: "{n} Spalten" },
        delimiterLabel: "Trennzeichen",
        tabLabel: "Tab",
        notInFile: "(nicht in dieser Datei)",
        columnFallback: "Spalte {n}",
        addedSugarNotice:
            "Diese Datei hat eine Spalte für zugesetzten Zucker ({column}), aber keine Spalte für Gesamtzucker, daher wurde Zucker nicht zugeordnet. Zucker wird als GESAMTZUCKER gespeichert, einschließlich des natürlich vorkommenden Zuckers in Obst und Milch — würde man zugesetzten Zucker dort zuordnen, würde jede Zeile zu niedrig ausgewiesen.",
        caffeineGramsNotice:
            "Die Koffeinspalte dieser Datei ({column}) ist in Gramm angegeben, Koffein wird hier aber in Milligramm gespeichert, daher wurde Koffein nicht zugeordnet. Eine Zuordnung würde 0,18 statt der angegebenen 180 mg erfassen. Ein späterer erneuter Import derselben Datei füllt das nicht nach — diese Zeilen sind dann bereits protokolliert und werden als Duplikate übersprungen. Falls die Spaltenüberschrift falsch beschriftet ist und die Werte tatsächlich in Milligramm vorliegen, wähle sie oben aus; sind sie wirklich in Gramm, multipliziere sie in der Datei vor dem Import mit 1000, nicht danach.",
        alcoholNotice:
            "Diese Datei hat eine Alkoholspalte ({column}), aber die Alkoholverfolgung ist für dieses Konto deaktiviert, daher wird sie nicht importiert. Ein späterer erneuter Import derselben Datei füllt das nicht nach — diese Zeilen sind dann bereits protokolliert und werden als Duplikate übersprungen. Um diese Daten zu behalten, bitte Claude, die Alkoholverfolgung (set_alcohol_tracking) vor dem Import zu aktivieren.",
        sampleValue: "z. B. {sample}",
        sourceAppLabel: "Quell-App (optional)",
        sourceAppHint:
            "Wird verwendet, um Zeilen ohne eigenen Lebensmittelnamen zu beschriften.",
        previewButton: "Import-Vorschau",
        chooseAnotherButton: "Andere Datei wählen",
        previewHeading: "Vorschau",
        mealsToImport: {
            one: "{n} Mahlzeit zu importieren",
            other: "{n} Mahlzeiten zu importieren",
        },
        kcalTotal: "{kcal} kcal insgesamt",
        rowsSkipped: "{n} Zeilen übersprungen",
        batchCount: { one: "{n} Stapel", other: "{n} Stapel" },
        datesReadAs: "Datumswerte gelesen als {format}; Energie {conversion}.",
        energyConvertedNote: "von kJ in kcal umgerechnet",
        energyReadAsKcal: "als kcal gelesen",
        badDatesWarning:
            "{n} Zeile(n) wurden übersprungen, weil das Datum nicht als {format} gelesen werden konnte{sample}. Geh zurück und stell das Datumsformat ein, das zu deiner Datei passt.",
        badDateSample: " (z. B. Zeile {line}: {value})",
        noTimeWarning:
            "{n} Zeile(n) haben ein Datum, aber keine Uhrzeit — sie werden für die Mittagszeit protokolliert.",
        splitDatesCount: {
            one: "{n} Datum hat",
            other: "{n} Datumswerte haben",
        },
        splitDatesWarning:
            " mehr als {max} Mahlzeiten (z. B. {date}); daher musste der Import auf mehrere Import-Stapel aufgeteilt werden. Enthält dieses Datum zwei Einträge mit exakt demselben Lebensmittel, derselben Mahlzeitenart und denselben Makros, kann einer davon als Duplikat übersprungen statt importiert werden.",
        tableLine: "Zeile",
        tableWhen: "Wann",
        tableMeal: "Mahlzeit",
        tableFood: "Lebensmittel",
        tableProblem: "Problem",
        noNameFallback: "(kein Name — wird nach Mahlzeit benannt)",
        showingRows: "Zeigt {shown} von {total} Zeilen",
        checkingRows: "{n} Zeilen werden geprüft…",
        importingRows: "{n} Zeilen werden importiert…",
        batchProgress: "{label} (Stapel {done} von {total})",
        rowsRange: "Zeilen {a}–{b}: {msg}",
        preflightFailed: "Vorabprüfung fehlgeschlagen.",
        rowsWouldFail:
            "{n} Zeile(n) würden fehlschlagen, z. B. Zeile {line}: {message}",
        importingEllipsis: "Wird importiert…",
        importButton: "{n} Mahlzeiten importieren",
        backToMapping: "Zurück zur Zuordnung",
        importCompleteHeading: "Import abgeschlossen",
        resultMealsImported: "{n} Mahlzeiten importiert",
        resultAlreadyLogged: ", {n} bereits protokolliert",
        resultFailed: ", {n} fehlgeschlagen",
        resultSkipped: ", {n} übersprungen",
        restartButton: "Weitere Datei importieren",
        couldNotReadFile: "Diese Datei konnte nicht gelesen werden: {msg}",
        noDataRows: "Keine Datenzeilen in dieser Datei gefunden.",
        emailNotice:
            "Funktioniert es nicht wie erwartet? Schreib an {email} und füg die untenstehenden Zeilen bei — damit lässt sich alles Nötige diagnostizieren.",
    },
};
