import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_UK: WidgetStrings = {
    macros: {
        labels: {
            calories: "Калорії",
            protein_g: "Білки",
            carbs_g: "Вуглеводи",
            fat_g: "Жири",
            sugar_g: "Цукор",
            alcohol_g: "Алкоголь",
            caffeine_mg: "Кофеїн",
            fiber_g: "Клітковина",
            water_ml: "Вода",
        },
        noGoalSet: "ціль не задана",
        atLimit: "на межі",
        floorUnder: "залишилось",
        ceilingUnder: "до ліміту",
        over: "перевищено",
        limitPrefix: "ліміт",
        ofPrefix: "з",
        drinkLabels: { us: "порції США", uk: "од. Великобританії" },
        noneLogged: "немає записів",
        tapHint: "Торкніться показника, щоб побачити страви",
        showMealsContributed: "Показати страви, що це склали.",
        byMealTitle: "{label} за стравами",
        closeBreakdown: "Закрити деталізацію",
        noMealsContributed: "Жодна із зареєстрованих страв не містить {label}.",
        untitledMeal: "Страва без назви",
        moreMeals: {
            one: "+ ще {n} менша страва",
            other: "+ ще {n} менших страв",
        },
    },
    nutritionSummary: {
        title: "Підсумок харчування",
        loading: "Завантаження підсумку харчування…",
        empty: "За цей період немає записів про страви чи воду.",
        caloriesPerDay: "Калорії / день",
        avg: "сер.",
        goal: "ціль",
        dailyAvgLoggedDays: "Середнє за день · дні з записами",
        total: "Всього",
        daysLogged: {
            one: "{n} день з записом",
            other: "{n} днів з записами",
        },
        daysOfLogged: "{logged} із {span} днів з записами",
        months: [
            "Січ",
            "Лют",
            "Бер",
            "Кві",
            "Тра",
            "Чер",
            "Лип",
            "Сер",
            "Вер",
            "Жов",
            "Лис",
            "Гру",
        ],
    },
};
