import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_JA: WidgetStrings = {
    macros: {
        labels: {
            calories: "カロリー",
            protein_g: "タンパク質",
            carbs_g: "炭水化物",
            fat_g: "脂質",
            sugar_g: "糖質",
            alcohol_g: "アルコール",
            caffeine_mg: "カフェイン",
            fiber_g: "食物繊維",
            water_ml: "水分",
        },
        noGoalSet: "目標未設定",
        atLimit: "上限に到達",
        floorUnder: "残り",
        ceilingUnder: "余裕",
        over: "超過",
        limitPrefix: "上限",
        ofPrefix: "目標",
        drinkLabels: { us: "US基準の杯数", uk: "UK基準のユニット" },
        noneLogged: "記録なし",
        tapHint: "数値をタップすると内訳の食事が表示されます",
        showMealsContributed: "内訳となった食事を表示します。",
        byMealTitle: "{label}の内訳",
        closeBreakdown: "内訳を閉じる",
        noMealsContributed: "{label}に該当する食事の記録がありません。",
        untitledMeal: "無題の食事",
        moreMeals: {
            one: "他 {n} 件の少量の食事",
            other: "他 {n} 件の少量の食事",
        },
    },
    nutritionSummary: {
        title: "栄養サマリー",
        loading: "栄養サマリーを読み込み中…",
        empty: "この期間に記録された食事や水分はありません。",
        caloriesPerDay: "1日あたりのカロリー",
        avg: "平均",
        goal: "目標",
        dailyAvgLoggedDays: "1日平均・記録日数",
        total: "合計",
        daysLogged: {
            one: "{n} 日分を記録",
            other: "{n} 日分を記録",
        },
        daysOfLogged: "{span} 日中 {logged} 日を記録",
        months: [
            "1月",
            "2月",
            "3月",
            "4月",
            "5月",
            "6月",
            "7月",
            "8月",
            "9月",
            "10月",
            "11月",
            "12月",
        ],
    },
    goalProgress: {
        title: "目標の進捗",
        empty: "表示できる目標の進捗はありません。",
        nothingLoggedFor: "{date}の記録はまだありません。",
        thisDay: "この日",
        mealsCount: { one: "食事 {n} 件", other: "食事 {n} 件" },
        waterCount: { one: "水分 {n} 件", other: "水分 {n} 件" },
        weightLabel: "体重",
        weightNoneNoTarget:
            "体重はまだ記録されていません。log_weightで記録すると進捗を追跡できます。",
        weightNoneWithTarget:
            "体重はまだ記録されていません。log_weightで記録すると、目標の{target}に向けた進捗を追跡できます。",
        weightNoGoal:
            "体重 {reading} — 目標未設定です。set_nutrition_goalsで設定すると、ここに進捗が表示されます。",
        atTarget: "目標達成",
        toLose: "あと{amount}減量",
        toGain: "あと{amount}増量",
        lastLogged: "最終記録：{date}",
        weightAria: "体重 {current}、目標 {target}、{state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "食事を記録しました",
        titleUpdated: "食事を更新しました",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "トレンド",
        empty: "この期間にはまだ食事や水分の記録がありません。",
        avgUnder: "不足",
        loggedOfTotal: "{logged}/{total} 日を記録",
        caloriesOverRange: "過去{range}日間の1日あたりカロリー",
        windowAriaLabel: "期間の切り替え",
        rangeDaysAriaLabel: "{n}日間",
        avgAllDays: "{range}日平均・全日",
    },
    weightTrends: {
        title: "体重",
        empty: "この期間にはまだ体重の記録がありません。",
        rangeEmpty:
            "過去{range}日間の体重記録がありません。期間を広げてお試しください。",
        windowAriaLabel: "期間の切り替え",
        rangeAriaLabel: "過去{n}日間",
        chartAriaLabel: "体重の推移：{from}から{to}、最新値 {latest}",
        latest: "最新",
        needTwo: "体重記録が2件以上必要です",
        sinceDate: "{date}から{change}",
        weighIns: { one: "体重記録 {n} 件", other: "体重記録 {n} 件" },
        atTarget: "目標達成",
        toLose: "あと{amount}減量",
        toGain: "あと{amount}増量",
        target: "目標 {value}",
        noTarget: "目標未設定",
    },
    importMeals: {
        stepFile: "ファイル",
        stepMap: "列の対応付け",
        stepPreview: "プレビュー",
        stepImport: "インポート",
        fieldLabels: {
            logged_at: "日付・時刻",
            description: "食品名",
            meal_type: "食事の種類",
            calories: "カロリー",
            protein_g: "タンパク質 (g)",
            carbs_g: "炭水化物 (g)",
            fat_g: "脂質 (g)",
            fiber_g: "食物繊維 (g)",
            sugar_g: "糖質（総量）(g)",
            alcohol_g: "アルコール (g)",
            caffeine_mg: "カフェイン (mg)",
            notes: "メモ",
            time: "時刻（別列）",
            deleted: "削除フラグ",
            source_id: "食事ID（本サービスのエクスポートから）",
            timezone: "タイムゾーン（本サービスのエクスポートから）",
        },
        chooseExportHeading: "エクスポートファイルを選択",
        noToolsWarning:
            "このホストではこの画面から記録を書き込めません。代わりにClaudeにファイルのインポートを依頼してください — Claudeが直接インポートできます。",
        emailFallback:
            "Claudeに依頼してもうまくいかない場合は、{email}までメールでご連絡ください。",
        tzWarning:
            "タイムゾーンが設定されていないため、時刻はUTCとして解釈され、日付がずれる場合があります。先にClaudeにタイムゾーンの設定を依頼してください。",
        dropChoose: "CSVファイルを選択",
        dropOr: "またはここにドラッグ",
        recognizedHint:
            "MyFitnessPal、Cronometer、Lose It!、MacroFactorのエクスポートは自動的に認識されます。確認するまで何も保存されません。",
        dateMapHint:
            "上で日付の列を選択すると、ファイルの値がどのように変換されるか確認できます。",
        dateNoneHint: "この列には日付が含まれていません。",
        dateUnreadable:
            "{raw} → {format}として読み取れないため、該当する行はスキップされます",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "上でカロリーの列を選択すると、ファイルの値がどのように変換されるか確認できます。",
        energyNoneHint: "この列には数値が含まれていません。",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal（変換なし）",
        dateAmbiguousWarning:
            "このファイルから日付の形式を判別できませんでした — 日付は「日が先」でも「月が先」でも矛盾なく解釈できます。お使いのアプリがどちらの形式でエクスポートするか確認してください。誤った形式を選ぶと、エラーなく間違った日に記録されてしまいます。",
        dateFormatLabel: "このファイルの日付形式",
        dateFormatYmd: "年-月-日",
        dateFormatDmy: "日/月/年",
        dateFormatMdy: "月/日/年",
        energyUnitLabel: "カロリー列のエネルギー単位",
        energyUnitKcal: "カロリー",
        energyUnitKj: "キロジュール",
        mapColumnsHeading: "列の対応付け",
        rowsCount: { one: "{n} 行", other: "{n} 行" },
        columnsCount: { one: "{n} 列", other: "{n} 列" },
        delimiterLabel: "区切り文字",
        tabLabel: "タブ",
        notInFile: "（このファイルにはありません）",
        columnFallback: "列 {n}",
        addedSugarNotice:
            "このファイルには「添加糖」の列（{column}）がありますが、「総糖質」の列がないため、糖質は対応付けされていません。糖質は果物や牛乳に自然に含まれるものも含めた「総量」として保存されるため、添加糖をそのまま対応付けると、すべての行で過小に記録されてしまいます。",
        caffeineGramsNotice:
            "このファイルのカフェイン列（{column}）はグラム単位ですが、カフェインはミリグラム単位で保存されるため、対応付けされていません。そのまま対応付けると、表示上180 mgのものが0.18として記録されてしまいます。後で同じファイルを再インポートしても補完されません — それらの行はすでに記録済みとして重複扱いでスキップされます。列名の表記が誤っていて実際の値がミリグラムである場合は上で選択してください。実際にグラムである場合は、インポート前（後ではなく）にファイル内で1000倍してください。",
        alcoholNotice:
            "このファイルにはアルコール列（{column}）がありますが、このアカウントではアルコールの記録がオフになっているため、インポートされません。後で同じファイルを再インポートしても補完されません — それらの行はすでに記録済みとして重複扱いでスキップされます。このデータを保持するには、インポート前にClaudeにアルコール記録の有効化（set_alcohol_tracking）を依頼してください。",
        sampleValue: "例：{sample}",
        sourceAppLabel: "元のアプリ（任意）",
        sourceAppHint:
            "食品名が入っていない行にラベルを付けるために使用されます。",
        previewButton: "インポート内容をプレビュー",
        chooseAnotherButton: "別のファイルを選択",
        previewHeading: "プレビュー",
        mealsToImport: {
            one: "インポート対象：{n} 件の食事",
            other: "インポート対象：{n} 件の食事",
        },
        kcalTotal: "合計 {kcal} kcal",
        rowsSkipped: "{n} 行をスキップ",
        batchCount: { one: "{n} バッチ", other: "{n} バッチ" },
        datesReadAs: "日付は{format}として読み取り、エネルギーは{conversion}。",
        energyConvertedNote: "kJからkcalに変換",
        energyReadAsKcal: "kcalとして読み取り",
        badDatesWarning:
            "{n} 件の行は、日付を{format}として読み取れなかったためスキップされました{sample}。戻ってファイルに合った日付形式を設定してください。",
        badDateSample: "（例：{line}行目：{value}）",
        noTimeWarning:
            "{n} 件の行には日付はありますが時刻がないため、正午として記録されます。",
        splitDatesCount: {
            one: "{n}件の日付で",
            other: "{n}件の日付で",
        },
        splitDatesWarning:
            "、{max}件を超える食事（例：{date}）があったため、複数のインポートバッチに分割されました。同じ日に食品名・食事の種類・栄養素がすべて同一の記録が2件ある場合、片方が重複としてスキップされ、インポートされないことがあります。",
        tableLine: "行",
        tableWhen: "日時",
        tableMeal: "食事",
        tableFood: "食品",
        tableProblem: "問題",
        noNameFallback: "（名前なし — 食事の種類でラベル付けされます）",
        showingRows: "{total}行中{shown}行を表示",
        checkingRows: "{n}行を確認中…",
        importingRows: "{n}行をインポート中…",
        batchProgress: "{label}（バッチ {done}/{total}）",
        rowsRange: "{a}〜{b}行目：{msg}",
        preflightFailed: "事前チェックに失敗しました。",
        rowsWouldFail:
            "{n} 件の行が失敗する見込みです（例：{line}行目：{message}）",
        importingEllipsis: "インポート中…",
        importButton: "{n}件の食事をインポート",
        backToMapping: "対応付けに戻る",
        importCompleteHeading: "インポート完了",
        resultMealsImported: "{n}件の食事をインポート",
        resultAlreadyLogged: "、{n}件は記録済み",
        resultFailed: "、{n}件が失敗",
        resultSkipped: "、{n}件をスキップ",
        restartButton: "別のファイルをインポート",
        couldNotReadFile: "ファイルを読み込めませんでした：{msg}",
        noDataRows: "そのファイルにデータ行が見つかりませんでした。",
        emailNotice:
            "うまく動作しませんか？{email}までメールでご連絡いただき、以下の内容を含めてください — 問題の診断に必要な情報がすべて含まれています。",
    },
};
