import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_IT: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calorie",
            protein_g: "Proteine",
            carbs_g: "Carboidrati",
            fat_g: "Grassi",
            sugar_g: "Zuccheri",
            alcohol_g: "Alcol",
            caffeine_mg: "Caffeina",
            fiber_g: "Fibre",
            water_ml: "Acqua",
        },
        noGoalSet: "nessun obiettivo impostato",
        atLimit: "al limite",
        floorUnder: "rimanenti",
        ceilingUnder: "sotto",
        over: "oltre",
        limitPrefix: "limite",
        ofPrefix: "di",
        drinkLabels: { us: "drink USA", uk: "unità UK" },
        noneLogged: "nessuno registrato",
        tapHint: "Tocca un valore per vedere i pasti che lo compongono",
        showMealsContributed: "Mostra i pasti che hanno contribuito.",
        byMealTitle: "{label} per pasto",
        closeBreakdown: "Chiudi il dettaglio",
        noMealsContributed: "Nessun pasto registrato ha contribuito a {label}.",
        untitledMeal: "Pasto senza titolo",
        moreMeals: {
            one: "+ {n} pasto più piccolo",
            other: "+ {n} pasti più piccoli",
        },
    },
    nutritionSummary: {
        title: "Riepilogo nutrizionale",
        loading: "Caricamento del riepilogo nutrizionale…",
        empty: "Nessun pasto o acqua registrati in questo periodo.",
        caloriesPerDay: "Calorie / giorno",
        avg: "media",
        goal: "obiettivo",
        dailyAvgLoggedDays: "Media giornaliera · giorni registrati",
        total: "Totale",
        daysLogged: {
            one: "{n} giorno registrato",
            other: "{n} giorni registrati",
        },
        daysOfLogged: "{logged} di {span} giorni registrati",
        months: [
            "gen",
            "feb",
            "mar",
            "apr",
            "mag",
            "giu",
            "lug",
            "ago",
            "set",
            "ott",
            "nov",
            "dic",
        ],
    },
    goalProgress: {
        title: "Progressi verso l'obiettivo",
        empty: "Nessun progresso da mostrare.",
        nothingLoggedFor: "Ancora nulla registrato per {date}.",
        thisDay: "questo giorno",
        mealsCount: { one: "{n} pasto", other: "{n} pasti" },
        waterCount: { one: "{n} acqua", other: "{n} acque" },
        weightLabel: "Peso",
        weightNoneNoTarget:
            "Nessun peso ancora registrato. Registrane uno con log_weight per monitorare i progressi.",
        weightNoneWithTarget:
            "Nessun peso ancora registrato. Registrane uno con log_weight per monitorare i progressi verso il tuo obiettivo di {target}.",
        weightNoGoal:
            "Peso {reading} — nessun obiettivo impostato. Impostane uno con set_nutrition_goals per vedere qui i progressi.",
        atTarget: "obiettivo raggiunto",
        toLose: "{amount} da perdere",
        toGain: "{amount} da guadagnare",
        lastLogged: "ultima registrazione {date}",
        weightAria: "Peso {current}, obiettivo {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Pasto registrato",
        titleUpdated: "Pasto aggiornato",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "Andamento",
        empty: "Ancora nessun pasto o acqua registrati in questo periodo.",
        avgUnder: "sotto",
        loggedOfTotal: "{logged}/{total} giorni registrati",
        caloriesOverRange: "Calorie al giorno negli ultimi {range} giorni",
        windowAriaLabel: "Intervallo di tempo",
        rangeDaysAriaLabel: "{n} giorni",
        avgAllDays: "media {range} giorni · tutti i giorni",
    },
    weightTrends: {
        title: "Peso",
        empty: "Ancora nessun peso registrato in questo periodo.",
        rangeEmpty:
            "Nessuna pesata negli ultimi {range} giorni. Prova un periodo più ampio.",
        windowAriaLabel: "Intervallo di tempo",
        rangeAriaLabel: "Ultimi {n} giorni",
        chartAriaLabel: "Peso da {from} a {to}, ultimo {latest}",
        latest: "Ultimo",
        needTwo: "servono almeno 2 pesate",
        sinceDate: "{change} da {date}",
        weighIns: { one: "{n} pesata", other: "{n} pesate" },
        atTarget: "obiettivo raggiunto",
        toLose: "{amount} da perdere",
        toGain: "{amount} da guadagnare",
        target: "Obiettivo {value}",
        noTarget: "Nessun obiettivo impostato",
    },
    importMeals: {
        stepFile: "File",
        stepMap: "Mappa colonne",
        stepPreview: "Anteprima",
        stepImport: "Importa",
        fieldLabels: {
            logged_at: "Data / ora",
            description: "Nome alimento",
            meal_type: "Pasto",
            calories: "Calorie",
            protein_g: "Proteine (g)",
            carbs_g: "Carboidrati (g)",
            fat_g: "Grassi (g)",
            fiber_g: "Fibre (g)",
            sugar_g: "Zuccheri, totali (g)",
            alcohol_g: "Alcol (g)",
            caffeine_mg: "Caffeina (mg)",
            notes: "Note",
            time: "Ora (colonna separata)",
            deleted: "Flag eliminato",
            source_id: "ID pasto (dalla nostra esportazione)",
            timezone: "Fuso orario (dalla nostra esportazione)",
        },
        chooseExportHeading: "Scegli la tua esportazione",
        noToolsWarning:
            "Questo host non permette a questa vista di scrivere nel tuo registro. Chiedi a Claude di importare il file al posto tuo — può farlo direttamente.",
        emailFallback:
            "Se anche chiedere a Claude non funziona, scrivi a {email}.",
        tzWarning:
            "Il tuo fuso orario non è impostato, quindi gli orari saranno letti come UTC e potrebbero finire nel giorno sbagliato. Chiedi prima a Claude di impostare il tuo fuso orario.",
        dropChoose: "Scegli un file CSV",
        dropOr: "oppure trascinalo qui",
        recognizedHint:
            "Le esportazioni da MyFitnessPal, Cronometer, Lose It! e MacroFactor vengono riconosciute automaticamente. Nulla viene salvato finché non confermi.",
        dateMapHint:
            "Mappa sopra una colonna di data per vedere come viene convertito un valore dal tuo file.",
        dateNoneHint: "Quella colonna non contiene date.",
        dateUnreadable:
            "{raw} → non può essere letto come {format}, quindi le righe simili verranno saltate",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Mappa sopra una colonna delle calorie per vedere come viene convertito un valore dal tuo file.",
        energyNoneHint: "Quella colonna non contiene numeri.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (nessuna conversione)",
        dateAmbiguousWarning:
            "Non è stato possibile determinare il formato della data da questo file — le sue date si leggono altrettanto bene con giorno o mese per primo. Conferma quale formato esporta la tua app: la scelta sbagliata registra i pasti nel giorno sbagliato senza alcun errore.",
        dateFormatLabel: "Formato data in questo file",
        dateFormatYmd: "Anno-Mese-Giorno",
        dateFormatDmy: "Giorno/Mese/Anno",
        dateFormatMdy: "Mese/Giorno/Anno",
        energyUnitLabel: "Unità di energia della colonna delle calorie",
        energyUnitKcal: "Calorie",
        energyUnitKj: "Chilojoule",
        mapColumnsHeading: "Mappa colonne",
        rowsCount: { one: "{n} riga", other: "{n} righe" },
        columnsCount: { one: "{n} colonna", other: "{n} colonne" },
        delimiterLabel: "delimitatore",
        tabLabel: "tabulazione",
        notInFile: "(non presente in questo file)",
        columnFallback: "colonna {n}",
        addedSugarNotice:
            "Questo file ha una colonna di zuccheri aggiunti ({column}) ma nessuna colonna di zuccheri totali, quindi Zuccheri è rimasto senza mappatura. Zuccheri viene memorizzato come zuccheri TOTALI, inclusi quelli naturalmente presenti in frutta e latte, quindi mappare qui gli zuccheri aggiunti sottostimerebbe ogni riga.",
        caffeineGramsNotice:
            "La colonna della caffeina di questo file ({column}) è in grammi, ma la caffeina viene memorizzata in milligrammi, quindi Caffeina è rimasta senza mappatura. Mapparla registrerebbe 0,18 dove l'etichetta indica 180 mg. Reimportare più tardi lo stesso file non la compilerà — quelle righe saranno già registrate e verranno saltate come duplicati. Se l'intestazione è etichettata male e i valori sono in realtà milligrammi, selezionala sopra; se sono davvero grammi, moltiplicali per 1000 nel file prima di importarlo, non dopo.",
        alcoholNotice:
            "Questo file ha una colonna dell'alcol ({column}), ma il monitoraggio dell'alcol è disattivato per questo account, quindi non verrà importata. Reimportare più tardi lo stesso file non la compilerà — quelle righe saranno già registrate e verranno saltate come duplicati. Per conservare questi dati, chiedi a Claude di attivare il monitoraggio dell'alcol (set_alcohol_tracking) prima di importare.",
        sampleValue: "es. {sample}",
        sourceAppLabel: "App di origine (opzionale)",
        sourceAppHint:
            "Usato per etichettare le righe che non hanno un proprio nome dell'alimento.",
        previewButton: "Anteprima importazione",
        chooseAnotherButton: "Scegli un altro file",
        previewHeading: "Anteprima",
        mealsToImport: {
            one: "{n} pasto da importare",
            other: "{n} pasti da importare",
        },
        kcalTotal: "{kcal} kcal totali",
        rowsSkipped: "{n} righe saltate",
        batchCount: { one: "{n} lotto", other: "{n} lotti" },
        datesReadAs: "Date lette come {format}; energia {conversion}.",
        energyConvertedNote: "convertita da kJ a kcal",
        energyReadAsKcal: "letta come kcal",
        badDatesWarning:
            "{n} riga/righe sono state saltate perché la loro data non poteva essere letta come {format}{sample}. Torna indietro e imposta il formato data corrispondente al tuo file.",
        badDateSample: " (es. riga {line}: {value})",
        noTimeWarning:
            "{n} riga/righe hanno una data ma nessun orario — verranno registrate a mezzogiorno.",
        splitDatesCount: {
            one: "{n} data ha",
            other: "{n} date hanno",
        },
        splitDatesWarning:
            " più di {max} pasti (es. {date}); l'importazione ha quindi dovuto essere suddivisa su più lotti separati. Se quella data contiene due voci con lo stesso identico alimento, tipo di pasto e macronutrienti, una di esse potrebbe essere saltata come duplicato invece di essere importata.",
        tableLine: "Riga",
        tableWhen: "Quando",
        tableMeal: "Pasto",
        tableFood: "Alimento",
        tableProblem: "Problema",
        noNameFallback: "(nessun nome — verrà etichettato in base al pasto)",
        showingRows: "Visualizzazione di {shown} righe su {total}",
        checkingRows: "Controllo di {n} righe…",
        importingRows: "Importazione di {n} righe…",
        batchProgress: "{label} (lotto {done} di {total})",
        rowsRange: "Righe {a}–{b}: {msg}",
        preflightFailed: "Il controllo preliminare non è riuscito.",
        rowsWouldFail:
            "{n} riga/righe non andrebbero a buon fine, es. riga {line}: {message}",
        importingEllipsis: "Importazione in corso…",
        importButton: "Importa {n} pasti",
        backToMapping: "Torna alla mappatura",
        importCompleteHeading: "Importazione completata",
        resultMealsImported: "{n} pasti importati",
        resultAlreadyLogged: ", {n} già registrati",
        resultFailed: ", {n} non riusciti",
        resultSkipped: ", {n} saltati",
        restartButton: "Importa un altro file",
        couldNotReadFile: "Impossibile leggere il file: {msg}",
        noDataRows: "Nessuna riga di dati trovata in quel file.",
        emailNotice:
            "Non funziona come previsto? Scrivi a {email} includendo le righe qui sotto — è tutto ciò che serve per diagnosticare il problema.",
    },
};
