import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_JA: WidgetStrings = {
    macros: {
        labels: {
            calories: "カロリー",
            protein_g: "タンパク質",
            carbs_g: "炭水化物",
            fat_g: "脂質",
            sugar_g: "糖質",
            alcohol_g: "アルコール",
            caffeine_mg: "カフェイン",
            fiber_g: "食物繊維",
            water_ml: "水分",
        },
        noGoalSet: "目標未設定",
        atLimit: "上限に到達",
        floorUnder: "残り",
        ceilingUnder: "余裕",
        over: "超過",
        limitPrefix: "上限",
        ofPrefix: "目標",
        drinkLabels: { us: "US基準の杯数", uk: "UK基準のユニット" },
        noneLogged: "記録なし",
        tapHint: "数値をタップすると内訳の食事が表示されます",
        showMealsContributed: "内訳となった食事を表示します。",
        byMealTitle: "{label}の内訳",
        closeBreakdown: "内訳を閉じる",
        noMealsContributed: "{label}に該当する食事の記録がありません。",
        untitledMeal: "無題の食事",
        moreMeals: {
            one: "他 {n} 件の少量の食事",
            other: "他 {n} 件の少量の食事",
        },
    },
    nutritionSummary: {
        title: "栄養サマリー",
        loading: "栄養サマリーを読み込み中…",
        empty: "この期間に記録された食事や水分はありません。",
        caloriesPerDay: "1日あたりのカロリー",
        avg: "平均",
        goal: "目標",
        dailyAvgLoggedDays: "1日平均・記録日数",
        total: "合計",
        daysLogged: {
            one: "{n} 日分を記録",
            other: "{n} 日分を記録",
        },
        daysOfLogged: "{span} 日中 {logged} 日を記録",
        months: [
            "1月",
            "2月",
            "3月",
            "4月",
            "5月",
            "6月",
            "7月",
            "8月",
            "9月",
            "10月",
            "11月",
            "12月",
        ],
    },
};
