import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_PL: WidgetStrings = {
    macros: {
        labels: {
            calories: "Kalorie",
            protein_g: "Białko",
            carbs_g: "Węglowodany",
            fat_g: "Tłuszcz",
            sugar_g: "Cukier",
            alcohol_g: "Alkohol",
            caffeine_mg: "Kofeina",
            fiber_g: "Błonnik",
            water_ml: "Woda",
        },
        noGoalSet: "brak celu",
        atLimit: "na limicie",
        floorUnder: "zostało",
        ceilingUnder: "poniżej",
        over: "powyżej",
        limitPrefix: "limit",
        ofPrefix: "z",
        drinkLabels: { us: "porcje (USA)", uk: "jednostki (UK)" },
        noneLogged: "brak wpisów",
        caloriesToday: "Kalorie dzisiaj",
        tapHint: "Dotknij wskaźnik, aby zobaczyć posiłki",
        showMealsContributed: "Pokaż posiłki, które się na to złożyły.",
        byMealTitle: "{label} według posiłków",
        closeBreakdown: "Zamknij szczegóły",
        noMealsContributed:
            "Żaden zapisany posiłek nie wniósł wartości {label}.",
        untitledMeal: "Posiłek bez nazwy",
        moreMeals: {
            one: "+ {n} mniejszy posiłek",
            other: "+ {n} mniejszych posiłków",
        },
    },
    nutritionSummary: {
        title: "Podsumowanie odżywiania",
        loading: "Wczytywanie podsumowania odżywiania…",
        empty: "Brak zapisanych posiłków lub wody w tym okresie.",
        caloriesPerDay: "Kalorie / dzień",
        chartAriaLabel: "Kalorie dziennie w wybranym zakresie",
        avg: "śr.",
        goal: "cel",
        dailyAvgLoggedDays: "Śr. dzienna · dni z wpisami",
        total: "Razem",
        daysLogged: {
            one: "{n} dzień z wpisem",
            other: "{n} dni z wpisami",
        },
        daysOfLogged: "{logged} z {span} dni z wpisami",
        months: [
            "Sty",
            "Lut",
            "Mar",
            "Kwi",
            "Maj",
            "Cze",
            "Lip",
            "Sie",
            "Wrz",
            "Paź",
            "Lis",
            "Gru",
        ],
    },
    goalProgress: {
        title: "Postęp celu",
        empty: "Brak postępu celu do wyświetlenia.",
        nothingLoggedFor: "Jeszcze nic nie zapisano dla {date}.",
        thisDay: "tego dnia",
        mealsCount: { one: "{n} posiłek", other: "{n} posiłków" },
        waterCount: { one: "{n} wpis wody", other: "{n} wpisów wody" },
        weightLabel: "Waga",
        weightNoneNoTarget:
            "Nie zapisano jeszcze wagi. Zapisz ją za pomocą log_weight, aby śledzić postępy.",
        weightNoneWithTarget:
            "Nie zapisano jeszcze wagi. Zapisz ją za pomocą log_weight, aby śledzić postępy w kierunku celu {target}.",
        weightNoGoal:
            "Waga {reading} — brak ustawionego celu. Ustaw go za pomocą set_nutrition_goals, aby zobaczyć tutaj postęp.",
        atTarget: "cel osiągnięty",
        toLose: "{amount} do zrzucenia",
        toGain: "{amount} do przybrania",
        lastLogged: "ostatnio zapisano {date}",
        weightAria: "Waga {current}, cel {target}, {state}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Posiłek zapisany",
        titleUpdated: "Posiłek zaktualizowany",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "Trendy",
        empty: "Jeszcze nie zapisano posiłków ani wody w tym okresie.",
        avgUnder: "poniżej",
        loggedOfTotal: "{logged}/{total} dni z wpisami",
        caloriesOverRange: "Kalorie dziennie w ciągu ostatnich {range} dni",
        windowAriaLabel: "Zakres trendu",
        rangeDaysAriaLabel: "{n} dni",
        avgAllDays: "Śr. z {range} dni · wszystkie dni",
    },
    weightTrends: {
        title: "Waga",
        empty: "Jeszcze nie zapisano wagi w tym okresie.",
        rangeEmpty:
            "Brak pomiarów wagi w ostatnich {range} dniach. Spróbuj szerszego zakresu.",
        windowAriaLabel: "Zakres trendu",
        rangeAriaLabel: "Ostatnie {n} dni",
        chartAriaLabel: "Waga od {from} do {to}, ostatnio {latest}",
        latest: "Najnowszy pomiar",
        needTwo: "potrzebne 2+ pomiary",
        sinceDate: "{change} od {date}",
        weighIns: { one: "{n} pomiar", other: "{n} pomiarów" },
        atTarget: "cel osiągnięty",
        toLose: "{amount} do zrzucenia",
        toGain: "{amount} do przybrania",
        target: "Cel {value}",
        noTarget: "Brak ustawionego celu",
    },
    importMeals: {
        stepFile: "Plik",
        stepMap: "Mapuj kolumny",
        stepPreview: "Podgląd",
        stepImport: "Import",
        fieldLabels: {
            logged_at: "Data / godzina",
            description: "Nazwa posiłku",
            meal_type: "Posiłek",
            calories: "Kalorie",
            protein_g: "Białko (g)",
            carbs_g: "Węglowodany (g)",
            fat_g: "Tłuszcz (g)",
            fiber_g: "Błonnik (g)",
            sugar_g: "Cukier, ogółem (g)",
            alcohol_g: "Alkohol (g)",
            caffeine_mg: "Kofeina (mg)",
            notes: "Notatki",
            time: "Godzina (osobna kolumna)",
            deleted: "Flaga usunięcia",
            source_id: "Identyfikator posiłku (z naszego eksportu)",
            timezone: "Strefa czasowa (z naszego eksportu)",
        },
        chooseExportHeading: "Wybierz swój eksport",
        noToolsWarning:
            "Ta aplikacja nie pozwala temu widokowi zapisywać danych w Twoim dzienniku. Poproś Claude, aby zamiast tego zaimportował plik — może zrobić to bezpośrednio.",
        emailFallback:
            "Jeśli poproszenie Claude również nie pomoże, napisz na {email}.",
        tzWarning:
            "Twoja strefa czasowa nie jest ustawiona, więc godziny zostaną odczytane jako UTC i mogą trafić na niewłaściwy dzień. Poproś najpierw Claude o ustawienie strefy czasowej.",
        dropChoose: "Wybierz plik CSV",
        dropOr: "lub przeciągnij go tutaj",
        recognizedHint:
            "Eksporty z MyFitnessPal, Cronometer, Lose It! i MacroFactor są rozpoznawane automatycznie. Nic nie zostanie zapisane, dopóki nie potwierdzisz.",
        dateMapHint:
            "Zmapuj powyżej kolumnę z datą, aby zobaczyć, jak wartość z Twojego pliku zostanie przekonwertowana.",
        dateNoneHint: "Ta kolumna nie zawiera dat.",
        dateUnreadable:
            "{raw} → nie można odczytać jako {format}, więc takie wiersze zostaną pominięte",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Zmapuj powyżej kolumnę z kaloriami, aby zobaczyć, jak wartość z Twojego pliku zostanie przekonwertowana.",
        energyNoneHint: "Ta kolumna nie zawiera liczb.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (bez konwersji)",
        dateAmbiguousWarning:
            "Nie udało się określić formatu daty w tym pliku — daty da się odczytać zarówno jako dzień-pierwszy, jak i miesiąc-pierwszy. Potwierdź, który format eksportuje Twoja aplikacja: błędny wybór zapisze posiłki w niewłaściwym dniu bez żadnego błędu.",
        dateFormatLabel: "Format daty w tym pliku",
        dateFormatYmd: "Rok-Miesiąc-Dzień",
        dateFormatDmy: "Dzień/Miesiąc/Rok",
        dateFormatMdy: "Miesiąc/Dzień/Rok",
        energyUnitLabel: "Jednostka energii w kolumnie kalorii",
        energyUnitKcal: "Kalorie",
        energyUnitKj: "Kilodżule",
        mapColumnsHeading: "Mapuj kolumny",
        rowsCount: { one: "{n} wiersz", other: "{n} wierszy" },
        columnsCount: { one: "{n} kolumna", other: "{n} kolumn" },
        delimiterLabel: "separator",
        tabLabel: "tabulator",
        notInFile: "(brak w tym pliku)",
        columnFallback: "kolumna {n}",
        addedSugarNotice:
            "Ten plik zawiera kolumnę cukrów dodanych ({column}), ale nie ma kolumny cukrów ogółem, więc Cukier pozostał niezmapowany. Cukier jest zapisywany jako cukry OGÓŁEM, w tym cukry naturalnie występujące w owocach i mleku, więc zmapowanie do niego cukrów dodanych zaniżałoby wynik w każdym wierszu.",
        caffeineGramsNotice:
            "Kolumna kofeiny w tym pliku ({column}) jest podana w gramach, ale kofeina jest zapisywana w miligramach, więc Kofeina pozostała niezmapowana. Zmapowanie jej zapisałoby 0,18 tam, gdzie etykieta mówi 180 mg. Ponowny import tego samego pliku później tego nie uzupełni — te wiersze będą już zapisane i zostaną pominięte jako duplikaty. Jeśli nagłówek jest błędnie oznaczony i wartości faktycznie są w miligramach, wybierz tę kolumnę powyżej; jeśli naprawdę są w gramach, pomnóż je przez 1000 w pliku przed importem, a nie po nim.",
        alcoholNotice:
            "Ten plik zawiera kolumnę alkoholu ({column}), ale śledzenie alkoholu jest wyłączone dla tego konta, więc nie zostanie zaimportowana. Ponowny import tego samego pliku później tego nie uzupełni — te wiersze będą już zapisane i zostaną pominięte jako duplikaty. Aby zachować te dane, poproś Claude o włączenie śledzenia alkoholu (set_alcohol_tracking) przed importem.",
        sampleValue: "np. {sample}",
        sourceAppLabel: "Aplikacja źródłowa (opcjonalnie)",
        sourceAppHint:
            "Używane do oznaczania wierszy, które nie mają własnej nazwy posiłku.",
        previewButton: "Podgląd importu",
        chooseAnotherButton: "Wybierz inny plik",
        previewHeading: "Podgląd",
        mealsToImport: {
            one: "{n} posiłek do zaimportowania",
            other: "{n} posiłków do zaimportowania",
        },
        kcalTotal: "{kcal} kcal łącznie",
        rowsSkipped: "{n} pominiętych wierszy",
        batchCount: { one: "{n} partia", other: "{n} partii" },
        datesReadAs: "Daty odczytywane jako {format}; energia {conversion}.",
        energyConvertedNote: "przekonwertowana z kJ na kcal",
        energyReadAsKcal: "odczytywana jako kcal",
        badDatesWarning:
            "Pominięto {n} wiersz(y), ponieważ ich data nie mogła zostać odczytana jako {format}{sample}. Wróć i ustaw format daty pasujący do Twojego pliku.",
        badDateSample: " (np. linia {line}: {value})",
        noTimeWarning:
            "{n} wiersz(y) ma datę, ale nie ma godziny — zostaną zapisane w południe.",
        splitDatesCount: {
            one: "{n} data ma",
            other: "{n} dat ma",
        },
        splitDatesWarning:
            " więcej niż {max} posiłków (np. {date}), więc trzeba było podzielić je na osobne partie importu. Jeśli ta data zawiera dwa wpisy z dokładnie tym samym jedzeniem, rodzajem posiłku i makroskładnikami, jeden z nich może zostać pominięty jako duplikat zamiast zaimportowany.",
        tableLine: "Linia",
        tableWhen: "Kiedy",
        tableMeal: "Posiłek",
        tableFood: "Jedzenie",
        tableProblem: "Problem",
        noNameFallback: "(brak nazwy — zostanie oznaczone jako posiłek)",
        showingRows: "Wyświetlanie {shown} z {total} wierszy",
        checkingRows: "Sprawdzanie {n} wierszy…",
        importingRows: "Importowanie {n} wierszy…",
        batchProgress: "{label} (partia {done} z {total})",
        rowsRange: "Wiersze {a}–{b}: {msg}",
        preflightFailed: "Kontrola wstępna nie powiodła się.",
        rowsWouldFail:
            "{n} wiersz(y) zakończy się błędem, np. linia {line}: {message}",
        importingEllipsis: "Importowanie…",
        importButton: "Importuj {n} posiłków",
        backToMapping: "Wróć do mapowania",
        importCompleteHeading: "Import zakończony",
        resultMealsImported: "Zaimportowano {n} posiłków",
        resultAlreadyLogged: ", {n} już zapisanych",
        resultFailed: ", {n} nieudanych",
        resultSkipped: ", {n} pominiętych",
        restartButton: "Zaimportuj kolejny plik",
        couldNotReadFile: "Nie udało się odczytać tego pliku: {msg}",
        noDataRows: "Nie znaleziono żadnych wierszy z danymi w tym pliku.",
        emailNotice:
            "Coś nie działa jak powinno? Napisz na {email} i dołącz poniższe linie — to wszystko, czego potrzeba do zdiagnozowania problemu.",
    },
};
