import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_DE: WidgetStrings = {
    macros: {
        labels: {
            calories: "Kalorien",
            protein_g: "Eiweiß",
            // Not the full "Kohlenhydrate": it truncates in the compact
            // three-column macro tile (visually confirmed against the
            // assembled widget) the way "Eiweiß"/"Fett" don't.
            carbs_g: "Kohlenh.",
            fat_g: "Fett",
            sugar_g: "Zucker",
            alcohol_g: "Alkohol",
            caffeine_mg: "Koffein",
            fiber_g: "Ballastst.",
            water_ml: "Wasser",
        },
        mealTypes: {
            breakfast: "Frühstück",
            lunch: "Mittagessen",
            dinner: "Abendessen",
            snack: "Snack",
        },
        noGoalSet: "kein Ziel festgelegt",
        atLimit: "am Limit",
        atGoal: "Ziel erreicht",
        floorUnder: "übrig",
        ceilingUnder: "unter",
        over: "über",
        limitPrefix: "Limit",
        ofPrefix: "von",
        drinkLabels: { us: "{n} US-Drinks", uk: "{n} UK-Einheiten" },
        noneLogged: "nichts protokolliert",
        caloriesToday: "Kalorien heute",
        caloriesOn: "Kalorien · {date}",
        tapHint: "Für die zugehörigen Mahlzeiten auf einen Wert tippen",
        showMealsContributed:
            "Zeigt die Mahlzeiten, die dazu beigetragen haben.",
        alsoChart: "Zeigt diesen Nährstoff außerdem im Diagramm an.",
        showOnChart: "Im Diagramm anzeigen.",
        showingMetric: "Zeigt {metric}. Zurück zu den Kalorien.",
        nameSep: ", ",
        nameEnd: ".",
        byMealTitle: "{label} nach Mahlzeit",
        closeBreakdown: "Aufschlüsselung schließen",
        noMealsContributed:
            "Keine protokollierten Mahlzeiten haben zu {label} beigetragen.",
        untitledMeal: "Unbenannte Mahlzeit",
        moreMeals: {
            one: "+ {n} kleinere Mahlzeit",
            other: "+ {n} kleinere Mahlzeiten",
        },
    },
    nutritionSummary: {
        title: "Ernährungsübersicht",
        loading: "Ernährungsübersicht wird geladen…",
        empty: "In diesem Zeitraum wurden keine Mahlzeiten oder kein Wasser protokolliert.",
        caloriesPerDay: "Kalorien / Tag",
        chartAriaLabel: "Kalorien pro Tag im ausgewählten Zeitraum",
        avg: "Ø",
        goal: "Ziel",
        dailyAvgLoggedDays: "Tagesmittel · erfasste Tage",
        total: "Gesamt",
        daysLogged: {
            one: "{n} Tag protokolliert",
            other: "{n} Tage protokolliert",
        },
        daysOfLogged: "{logged} von {span} Tagen protokolliert",
        months: [
            "Jan",
            "Feb",
            "Mär",
            "Apr",
            "Mai",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Okt",
            "Nov",
            "Dez",
        ],
    },
    goalProgress: {
        title: "Zielfortschritt",
        empty: "Kein Zielfortschritt anzuzeigen.",
        nothingLoggedFor: "Für {date} noch nichts protokolliert.",
        thisDay: "diesen Tag",
        mealsCount: { one: "{n} Mahlzeit", other: "{n} Mahlzeiten" },
        waterCount: { one: "{n} Wasser", other: "{n} Wasser" },
        weightLabel: "Gewicht",
        weightNoneNoTarget:
            "Noch kein Gewicht protokolliert. Protokolliere eins mit log_weight, um den Fortschritt zu verfolgen.",
        weightNoneWithTarget:
            "Noch kein Gewicht protokolliert. Protokolliere eins mit log_weight, um den Fortschritt zu deinem Ziel von {target} zu verfolgen.",
        weightNoGoal:
            "Gewicht {reading} — kein Ziel festgelegt. Leg eins mit set_nutrition_goals fest, um hier den Fortschritt zu sehen.",
        atTarget: "am Ziel",
        toLose: "{amount} bis zum Ziel (abnehmen)",
        toGain: "{amount} bis zum Ziel (zunehmen)",
        lastLogged: "zuletzt protokolliert am {date}",
        weightAria: "Gewicht {current}, Ziel {target}, {state}{metaSuffix}",
        loading: "Zielfortschritt wird geladen…",
        nothingLogged: "Noch nichts protokolliert.",
        lastLoggedSuffix: ", zuletzt protokolliert am {date}",
        weightAriaNoTarget: "Gewicht {current}{metaSuffix}",
    },
    mealLogged: {
        titleLogged: "Mahlzeit protokolliert",
        titleUpdated: "Mahlzeit aktualisiert",
        addedKcal: "+{kcal} kcal",
    },
    trends: {
        title: "Trends",
        empty: "In diesem Zeitraum wurden noch keine Mahlzeiten oder kein Wasser protokolliert.",
        avgUnder: "unter",
        caloriesOverRange: "Kalorien pro Tag in den letzten {range} Tagen",
        metricOverRange: "{metric} pro Tag in den letzten {range} Tagen",
        windowAriaLabel: "Trendzeitraum",
        rangeDaysAriaLabel: "{n} Tage",
        avgAllDays: "{range}-Tage-Ø · alle Tage",
        loading: "Trends werden geladen…",
        rangeEmpty:
            "In den letzten {range} Tagen nichts protokolliert. Versuch einen größeren Zeitraum.",
        metricAvgAllDays: "{metric} · {range}-Tage-Ø · alle Tage",
        metricAvgRecorded: "{metric} · {range}-Tage-Ø · erfasste Tage",
    },
    weightTrends: {
        title: "Gewicht",
        empty: "In diesem Zeitraum wurde noch kein Gewicht protokolliert.",
        rangeEmpty: "Keine Wiegungen in den letzten {range} Tagen.",
        windowAriaLabel: "Trendzeitraum",
        rangeAriaLabel: "Letzte {n} Tage",
        chartAriaLabel: "Gewicht von {from} bis {to}, zuletzt {latest}",
        latest: "Zuletzt",
        needTwo: "mindestens 2 Wiegungen nötig",
        sinceDate: "{change} seit {date}",
        weighIns: { one: "{n} Wiegung", other: "{n} Wiegungen" },
        atTarget: "am Ziel",
        // Short forms, like every other locale's ("{amount} af te vallen",
        // "{amount} do zrzucenia"). "{amount} bis zum Ziel (abnehmen)" both
        // restated "Ziel" and added a parenthetical, and this line ends in
        // " · Ziel 75,0 kg" whose figure is the only part allowed to give
        // (`.fgive`) — so at 280px German, and German alone, printed the gloss
        // in full and cut the target weight mid-figure ("75,").
        toLose: "noch {amount} abnehmen",
        toGain: "noch {amount} zunehmen",
        target: "Ziel {value}",
        noTarget: "Kein Ziel festgelegt",
        loading: "Gewichtsverlauf wird geladen…",
    },
    importMeals: {
        stepFile: "Datei",
        stepMap: "Spalten zuordnen",
        stepPreview: "Vorschau",
        stepImport: "Import",
        loading: "Import wird vorbereitet…",
        stepCount: "Schritt {n} von {total}",
        requiredLegend: "Mit * markierte Felder sind Pflichtfelder.",
        fieldLabels: {
            logged_at: "Datum / Uhrzeit",
            description: "Name des Lebensmittels",
            meal_type: "Mahlzeit",
            calories: "Kalorien",
            protein_g: "Eiweiß (g)",
            carbs_g: "Kohlenhydrate (g)",
            fat_g: "Fett (g)",
            fiber_g: "Ballaststoffe (g)",
            sugar_g: "Zucker, gesamt (g)",
            alcohol_g: "Alkohol (g)",
            caffeine_mg: "Koffein (mg)",
            notes: "Notizen",
            time: "Uhrzeit (eigene Spalte)",
            deleted: "Gelöscht-Kennzeichen",
            source_id: "Mahlzeit-ID (aus unserem Export)",
            timezone: "Zeitzone (aus unserem Export)",
        },
        chooseExportHeading: "Wähle deinen Export",
        noToolsWarning:
            "Dieser Host erlaubt dieser Ansicht nicht, in dein Protokoll zu schreiben. Bitte Claude, die Datei stattdessen zu importieren — das kann Claude direkt erledigen.",
        emailFallback:
            "Falls auch das Bitten von Claude nicht funktioniert, schreib an {email}.",
        tzWarning:
            "Deine Zeitzone ist nicht festgelegt, daher werden Uhrzeiten als UTC gelesen und können auf den falschen Tag fallen. Bitte Claude, zuerst deine Zeitzone festzulegen.",
        dropChoose: "CSV-Datei auswählen",
        dropOr: "oder hierher ziehen",
        recognizedHint:
            "Exporte von MyFitnessPal, Cronometer, Lose It! und MacroFactor werden automatisch erkannt. Es wird nichts gespeichert, bevor du bestätigst.",
        dateMapHint:
            "Ordne oben eine Datumsspalte zu, um zu sehen, wie ein Wert aus deiner Datei umgewandelt wird.",
        dateNoneHint: "Diese Spalte enthält keine Datumswerte.",
        dateUnreadable:
            "{raw} → kann nicht als {format} gelesen werden, solche Zeilen werden übersprungen",
        dateConverted: "{raw} → {result}",
        energyMapHint:
            "Ordne oben eine Kalorienspalte zu, um zu sehen, wie ein Wert aus deiner Datei umgewandelt wird.",
        energyNoneHint: "Diese Spalte enthält keine Zahlen.",
        energyConverted: "{v} kJ → {kcal} kcal",
        energyNoConversion: "{v} kcal → {v} kcal (keine Umrechnung)",
        dateAmbiguousWarning:
            "Das Datumsformat konnte aus dieser Datei nicht bestimmt werden — die Datumswerte lassen sich sowohl tag- als auch monatsführend lesen. Bitte bestätige, welches Format deine App exportiert: die falsche Wahl protokolliert Mahlzeiten am falschen Tag, ohne einen Fehler anzuzeigen.",
        dateFormatLabel: "Datumsformat in dieser Datei",
        dateFormatYmd: "Jahr-Monat-Tag",
        dateFormatDmy: "Tag/Monat/Jahr",
        dateFormatMdy: "Monat/Tag/Jahr",
        energyUnitLabel: "Energieeinheit der Kalorienspalte",
        energyUnitKcal: "Kalorien",
        energyUnitKj: "Kilojoule",
        mapColumnsHeading: "Spalten zuordnen",
        rowsCount: { one: "{n} Zeile", other: "{n} Zeilen" },
        columnsCount: { one: "{n} Spalte", other: "{n} Spalten" },
        delimiterLabel: "Trennzeichen",
        tabLabel: "Tab",
        notInFile: "(nicht in dieser Datei)",
        columnFallback: "Spalte {n}",
        addedSugarNotice:
            "Diese Datei hat eine Spalte für zugesetzten Zucker ({column}), aber keine Spalte für Gesamtzucker, daher wurde Zucker nicht zugeordnet. Zucker wird als GESAMTZUCKER gespeichert, einschließlich des natürlich vorkommenden Zuckers in Obst und Milch — würde man zugesetzten Zucker dort zuordnen, würde jede Zeile zu niedrig ausgewiesen.",
        caffeineGramsNotice:
            "Die Koffeinspalte dieser Datei ({column}) ist in Gramm angegeben, Koffein wird hier aber in Milligramm gespeichert, daher wurde Koffein nicht zugeordnet. Eine Zuordnung würde 0,18 statt der angegebenen 180 mg erfassen. Ein späterer erneuter Import derselben Datei füllt das nicht nach — diese Zeilen sind dann bereits protokolliert und werden als Duplikate übersprungen. Falls die Spaltenüberschrift falsch beschriftet ist und die Werte tatsächlich in Milligramm vorliegen, wähle sie oben aus; sind sie wirklich in Gramm, multipliziere sie in der Datei vor dem Import mit 1000, nicht danach.",
        alcoholNotice:
            "Diese Datei hat eine Alkoholspalte ({column}), aber die Alkoholverfolgung ist für dieses Konto deaktiviert, daher wird sie nicht importiert. Ein späterer erneuter Import derselben Datei füllt das nicht nach — diese Zeilen sind dann bereits protokolliert und werden als Duplikate übersprungen. Um diese Daten zu behalten, bitte Claude, die Alkoholverfolgung (set_alcohol_tracking) vor dem Import zu aktivieren.",
        sampleValue: "z. B. {sample}",
        sourceAppLabel: "Quell-App (optional)",
        sourceAppHint:
            "Wird verwendet, um Zeilen ohne eigenen Lebensmittelnamen zu beschriften.",
        previewButton: "Import-Vorschau",
        chooseAnotherButton: "Andere Datei wählen",
        previewHeading: "Vorschau",
        mealsToImport: {
            one: "{n} Mahlzeit zu importieren",
            other: "{n} Mahlzeiten zu importieren",
        },
        kcalTotal: "{kcal} kcal insgesamt",
        batchCount: { one: "{n} Stapel", other: "{n} Stapel" },
        datesReadAs: "Datumswerte gelesen als {format}; Energie {conversion}.",
        energyConvertedNote: "von kJ in kcal umgerechnet",
        energyReadAsKcal: "als kcal gelesen",
        badDateSample: " (z. B. Zeile {line}: {value})",
        splitDatesCount: {
            one: "{n} Datum hat",
            other: "{n} Datumswerte haben",
        },
        splitDatesWarning:
            " mehr als {max} Mahlzeiten (z. B. {date}); daher musste der Import auf mehrere Import-Stapel aufgeteilt werden. Enthält dieses Datum zwei Einträge mit exakt demselben Lebensmittel, derselben Mahlzeitenart und denselben Makros, kann einer davon als Duplikat übersprungen statt importiert werden.",
        tableLine: "Zeile",
        tableWhen: "Wann",
        tableMeal: "Mahlzeit",
        tableFood: "Lebensmittel",
        tableProblem: "Problem",
        colProtein: "Eiw.",
        colCarbs: "KH",
        colFat: "Fett",
        colFiber: "Ballastst.",
        colSugar: "Zucker",
        colAlcohol: "Alk.",
        colCaffeine: "Koff.",
        noNameFallback: "(kein Name — wird nach Mahlzeit benannt)",
        batchProgress: "{label} (Stapel {done} von {total})",
        rowsRange: "Zeilen {a}–{b}: {msg}",
        preflightFailed: "Vorabprüfung fehlgeschlagen.",
        importingEllipsis: "Wird importiert…",
        backToMapping: "Zurück zur Zuordnung",
        importCompleteHeading: "Import abgeschlossen",
        restartButton: "Weitere Datei importieren",
        noTimeWarning: {
            one: "{n} Zeile hat ein Datum, aber keine Uhrzeit — sie wird für die Mittagszeit protokolliert.",
            other: "{n} Zeilen haben ein Datum, aber keine Uhrzeit — sie werden für die Mittagszeit protokolliert.",
        },
        rowsSkipped: {
            one: "{n} Zeile übersprungen",
            other: "{n} Zeilen übersprungen",
        },
        badDatesWarning: {
            one: "{n} Zeile wurde übersprungen, weil ihr Datum nicht als {format} gelesen werden konnte{sample}. Geh zurück und stell das Datumsformat ein, das zu deiner Datei passt.",
            other: "{n} Zeilen wurden übersprungen, weil ihr Datum nicht als {format} gelesen werden konnte{sample}. Geh zurück und stell das Datumsformat ein, das zu deiner Datei passt.",
        },
        rowsWouldFail: {
            one: "{n} Zeile würde fehlschlagen, z. B. Zeile {line}: {message}",
            other: "{n} Zeilen würden fehlschlagen, z. B. Zeile {line}: {message}",
        },
        resultMealsImported: {
            one: "{n} Mahlzeit importiert",
            other: "{n} Mahlzeiten importiert",
        },
        importButton: {
            one: "{n} Mahlzeit importieren",
            other: "{n} Mahlzeiten importieren",
        },
        checkingRows: {
            one: "{n} Zeile wird geprüft…",
            other: "{n} Zeilen werden geprüft…",
        },
        importingRows: {
            one: "{n} Zeile wird importiert…",
            other: "{n} Zeilen werden importiert…",
        },
        showingRows: {
            one: "Zeigt {shown} von {total} Zeile",
            other: "Zeigt {shown} von {total} Zeilen",
        },
        resultAlreadyLogged: {
            one: ", {n} bereits protokolliert",
            other: ", {n} bereits protokolliert",
        },
        resultFailed: {
            one: ", {n} fehlgeschlagen",
            other: ", {n} fehlgeschlagen",
        },
        resultSkipped: {
            one: ", {n} übersprungen",
            other: ", {n} übersprungen",
        },
        sentenceEnd: ".",
        couldNotReadFile: "Diese Datei konnte nicht gelesen werden: {msg}",
        noDataRows: "Keine Datenzeilen in dieser Datei gefunden.",
        emailNotice:
            "Funktioniert es nicht wie erwartet? Schreib an {email} und füg die untenstehenden Zeilen bei — damit lässt sich alles Nötige diagnostizieren.",
    },
    // German labels (LMIV / DIN 1301) write the litre lowercase — "2,5 l",
    // "250 ml". A pound stays "lb": the German "Pfund" is a colloquial
    // 500 g, so a translated "Pfd." would read as the wrong mass.
    units: {
        kcal: "kcal",
        kj: "kJ",
        g: "g",
        mg: "mg",
        ml: "ml",
        l: "l",
        fl_oz: "fl oz",
        kg: "kg",
        lb: "lb",
    },
    chrome: {
        widgetsNote:
            "Du kannst diese Widgets jederzeit ein- oder ausschalten — bitte einfach darum, deine Einstellungen zu ändern.",
        noHost: "Diese Ansicht konnte keine Verbindung zu ihrem Host herstellen.",
    },
};
