import type { WidgetStrings } from "./widgets.js";

export const WIDGET_STRINGS_IT: WidgetStrings = {
    macros: {
        labels: {
            calories: "Calorie",
            protein_g: "Proteine",
            carbs_g: "Carboidrati",
            fat_g: "Grassi",
            sugar_g: "Zuccheri",
            alcohol_g: "Alcol",
            caffeine_mg: "Caffeina",
            fiber_g: "Fibre",
            water_ml: "Acqua",
        },
        noGoalSet: "nessun obiettivo impostato",
        atLimit: "al limite",
        floorUnder: "rimanenti",
        ceilingUnder: "sotto",
        over: "oltre",
        limitPrefix: "limite",
        ofPrefix: "di",
        drinkLabels: { us: "drink USA", uk: "unità UK" },
        noneLogged: "nessuno registrato",
        tapHint: "Tocca un valore per vedere i pasti che lo compongono",
        showMealsContributed: "Mostra i pasti che hanno contribuito.",
        byMealTitle: "{label} per pasto",
        closeBreakdown: "Chiudi il dettaglio",
        noMealsContributed: "Nessun pasto registrato ha contribuito a {label}.",
        untitledMeal: "Pasto senza titolo",
        moreMeals: {
            one: "+ {n} pasto più piccolo",
            other: "+ {n} pasti più piccoli",
        },
    },
    nutritionSummary: {
        title: "Riepilogo nutrizionale",
        loading: "Caricamento del riepilogo nutrizionale…",
        empty: "Nessun pasto o acqua registrati in questo periodo.",
        caloriesPerDay: "Calorie / giorno",
        avg: "media",
        goal: "obiettivo",
        dailyAvgLoggedDays: "Media giornaliera · giorni registrati",
        total: "Totale",
        daysLogged: {
            one: "{n} giorno registrato",
            other: "{n} giorni registrati",
        },
        daysOfLogged: "{logged} di {span} giorni registrati",
        months: [
            "gen",
            "feb",
            "mar",
            "apr",
            "mag",
            "giu",
            "lug",
            "ago",
            "set",
            "ott",
            "nov",
            "dic",
        ],
    },
};
