/**
 * Generates the two assets the landing page's in-chat widget cards need at
 * RUNTIME — the scoped stylesheet and the deferred interaction runtime — plus
 * one tiny strings file per locale.
 *
 *   public/widget-card.css          the widget's own CSS, scoped to
 *                                   `.nm-widget-card` (src/widget-css.ts)
 *   public/widget-card.js           every shared JS partial the two card
 *                                   templates include, minus shared/bridge.js,
 *                                   plus public/widgets/src/site/boot.js
 *   public/widget-card.<locale>.js  that locale's slice of WIDGET_STRINGS
 *                                   (plus `en`, always), ~2 KB each
 *
 * WHY GENERATED AND NOT HAND-PORTED. The cards on the landing page are
 * rendered at build time by the real emitters (scripts/gen-index.ts), so their
 * MARKUP cannot drift from chat. A hand-copied stylesheet or a hand-copied
 * runtime would make the other two halves the ones that drift silently — the
 * page would keep rendering and keep looking almost right. Both are therefore
 * built from the same sources the widgets themselves are assembled from
 * (src/widgets.ts's readSrc/resolveIncludes), and the partial LIST is read out
 * of the templates' own `@include` markers rather than typed here, so a
 * template that gains a partial gains it on the site too.
 *
 * WHY THE STRINGS ARE SPLIT OUT. The full nine-locale WIDGET_STRINGS is ~32 KB
 * of JSON; the runtime is the same bytes on all nine locale pages. Splitting
 * them means one cacheable /widget-card.js shared across /de/, /ja/, … and a
 * ~2 KB per-locale file beside it, instead of nine near-identical bundles.
 * Only the namespaces the bundle actually reaches for (`T.<ns>`) are emitted,
 * scanned out of the built code rather than listed here — import-meals' string
 * table is more than half the dictionary and no landing card can reach it.
 *
 * Load order on the page (both `defer`, so they run in document order):
 *
 *     <link rel="stylesheet" href="/widget-card.css">
 *     <script defer src="/widget-card.de.js"></script>
 *     <script defer src="/widget-card.js"></script>
 *
 * Re-run after editing any shared widget partial, public/widgets/src/site/
 * boot.js, or src/copy/widgets.ts:
 *   bun run scripts/gen-widget-card.ts
 * The generated files are the served artifacts (src/index.ts) and are listed
 * in .prettierignore — don't hand-edit them.
 */

import { buildWidgetCardCss } from "../src/widget-css.js";
import { readSrc, resolveIncludes } from "../src/widgets.js";
import { WIDGET_STRINGS } from "../src/copy/widgets.js";
import { SITE_LOCALES, type SiteLocale } from "../src/routes.js";

/** The templates whose cards the landing page ships. The partial list comes
 *  from THEIR `@include` markers, in their order. */
const CARD_TEMPLATES = ["nutrition-summary.html", "trends.html"] as const;

/** The one partial the page must not load: it is the MCP-host handshake —
 *  a postMessage protocol, an iframe resize observer and a settings-note
 *  MutationObserver, none of which exist outside a chat host. boot.js says
 *  which three of its helpers that costs and what replaces them. */
const EXCLUDED = new Set(["shared/bridge.js"]);

/** boot.js is appended last, after every partial it calls. */
const BOOT = "site/boot.js";

/** Where the per-locale dictionary lands. Read by shared/i18n.js through the
 *  `WIDGET_STRINGS` binding the bundle opens with. */
const STRINGS_GLOBAL = "window.NM_WIDGET_STRINGS";

/* Size budgets, so the bundle cannot creep silently. Raw bytes, checked after
   every build; they sit ~20% over what the tree currently produces, which is
   room for a partial or two and not room for a stray dependency. Raise one
   deliberately, in the same commit as whatever grew. */
const BUDGETS = {
    css: 45_000,
    js: 62_000,
    strings: 8_000,
} as const;

const INCLUDE_RE = /\/\*@include\s+([^\s@]+)\s*@\*\//g;

function banner(what: string): string {
    return (
        `/* ${what}\n` +
        `   GENERATED by scripts/gen-widget-card.ts — do not edit.\n` +
        `   Sources: public/widgets/src/ (the same partials the in-chat\n` +
        `   widgets are assembled from) — edit those and re-run the script. */\n`
    );
}

/** Every `.js` partial a template includes, in the template's own order. */
function jsIncludes(template: string): string[] {
    const out: string[] = [];
    for (const m of template.matchAll(INCLUDE_RE)) {
        const rel = m[1]!;
        if (!rel.endsWith(".js") || EXCLUDED.has(rel)) continue;
        if (!out.includes(rel)) out.push(rel);
    }
    return out;
}

/** Merge the templates' lists into one order that satisfies all of them.
 *  Appending each template's new partials at the end is enough here (the two
 *  cards differ only in their last partial), but "enough here" is exactly the
 *  kind of claim that stops being true quietly — so the result is checked
 *  against every template's own order and the build fails if it disagrees. */
function mergeOrder(lists: string[][]): string[] {
    const merged: string[] = [];
    for (const list of lists) {
        for (const rel of list) if (!merged.includes(rel)) merged.push(rel);
    }
    for (const list of lists) {
        let at = -1;
        for (const rel of list) {
            const i = merged.indexOf(rel);
            if (i < at) {
                throw new Error(
                    `gen-widget-card: the card templates include their partials in incompatible orders (${rel} moves backwards) — order them by hand here`,
                );
            }
            at = i;
        }
    }
    return merged;
}

/** The namespaces the built code reads off the ambient `T` (shared/i18n.js).
 *  Scanned rather than listed: a partial that starts reading a new one starts
 *  shipping it, and one that stops stops. */
function usedNamespaces(js: string): string[] {
    const found = new Set<string>();
    for (const m of js.matchAll(/\bT\.([A-Za-z_$][\w$]*)/g)) found.add(m[1]!);
    if (/\bT\s*\[/.test(js)) {
        throw new Error(
            "gen-widget-card: the bundle indexes T dynamically (`T[...]`), so the namespaces it needs cannot be scanned — ship the whole dictionary or keep the access static",
        );
    }
    if (!found.size) {
        throw new Error("gen-widget-card: no `T.<namespace>` use found");
    }
    return [...found].sort();
}

function pickNamespaces(
    strings: Record<string, unknown>,
    namespaces: string[],
): Record<string, unknown> {
    const out: Record<string, unknown> = {};
    for (const ns of namespaces) {
        if (ns in strings) out[ns] = strings[ns];
    }
    return out;
}

function sizes(text: string): string {
    const raw = Buffer.byteLength(text);
    const gz = Bun.gzipSync(Buffer.from(text)).length;
    return `${(raw / 1024).toFixed(1)} KB raw, ${(gz / 1024).toFixed(1)} KB gzip`;
}

function budget(name: string, text: string, max: number): void {
    const raw = Buffer.byteLength(text);
    if (raw > max) {
        throw new Error(
            `gen-widget-card: ${name} is ${raw} bytes, over its ${max}-byte budget. Something grew — check what, then raise the budget in this file deliberately.`,
        );
    }
}

async function main(): Promise<void> {
    /* ---- the stylesheet. The whole transform, and every assertion that it
       cannot leak outside the card, lives in src/widget-css.ts. */
    const css =
        banner("The in-chat widget CSS, scoped to .nm-widget-card.\n") +
        (await buildWidgetCardCss());

    /* ---- the runtime */
    const lists: string[][] = [];
    for (const file of CARD_TEMPLATES) {
        lists.push(jsIncludes(await readSrc(`templates/${file}`)));
    }
    const partials = mergeOrder(lists);
    if (!partials.length) {
        throw new Error(
            "gen-widget-card: no JS partials found in the card templates — did the @include markers change shape?",
        );
    }

    let source = "";
    for (const rel of [...partials, BOOT]) {
        // Through resolveIncludes, so a partial that grows an @include of its
        // own is expanded exactly as the widget assembler expands it.
        source +=
            (await resolveIncludes(await readSrc(rel), rel, [rel])) + "\n";
    }
    // Comments are ~75% of these files and every one of them is in the repo.
    // Bun's transpiler is the stripper rather than a regex: these partials are
    // full of regex literals and template literals whose whitespace is part of
    // the painted markup, and it leaves both byte-for-byte.
    const stripped = new Bun.Transpiler({ loader: "js" }).transformSync(source);

    const namespaces = usedNamespaces(stripped);

    const js =
        banner("The in-chat widget runtime for the public site.\n") +
        // One IIFE: these partials declare MACROS, T, fmt, esc, RANGES and
        // three dozen more at their top level, and the page has its own
        // globals (public/site.js). "use strict", as every widget template's
        // own <script> already opens with.
        `(function () {\n"use strict";\n` +
        `const WIDGET_STRINGS = ${STRINGS_GLOBAL} || null;\n` +
        // The strings file is a separate, per-locale <script> that must come
        // first. Missing, the cards stay exactly as the server rendered them:
        // static, complete and readable, minus the interactions.
        `if (!WIDGET_STRINGS || !WIDGET_STRINGS.en) {\n` +
        `    try { console.warn("[widget-card] no ${STRINGS_GLOBAL}; cards stay static"); } catch (e) {}\n` +
        `    return;\n}\n` +
        stripped +
        `})();\n`;

    // Parses, and parses as a whole: a partial that is fine on its own but
    // redeclares something another one already declared fails here rather than
    // in a visitor's console.
    new Function(js);

    /* ---- the per-locale strings */
    const strings = new Map<SiteLocale, string>();
    for (const locale of SITE_LOCALES) {
        const dict = WIDGET_STRINGS[locale];
        if (!dict) {
            throw new Error(
                `gen-widget-card: WIDGET_STRINGS has no "${locale}" — every site locale must have one, or shared/i18n.js falls the page back to English silently`,
            );
        }
        // `en` always rides along: shared/i18n.js initialises T to
        // WIDGET_STRINGS.en, before any locale is resolved.
        const payload: Record<string, unknown> = {
            en: pickNamespaces(
                WIDGET_STRINGS.en as unknown as Record<string, unknown>,
                namespaces,
            ),
        };
        if (locale !== "en") {
            payload[locale] = pickNamespaces(
                dict as unknown as Record<string, unknown>,
                namespaces,
            );
        }
        strings.set(
            locale,
            banner(
                `Widget UI strings for "${locale}" (and the "en" fallback).\n`,
            ) + `${STRINGS_GLOBAL} = ${JSON.stringify(payload)};\n`,
        );
    }

    /* ---- budgets, then disk */
    budget("public/widget-card.css", css, BUDGETS.css);
    budget("public/widget-card.js", js, BUDGETS.js);
    for (const [locale, text] of strings) {
        budget(`public/widget-card.${locale}.js`, text, BUDGETS.strings);
    }

    await Bun.write("public/widget-card.css", css);
    await Bun.write("public/widget-card.js", js);
    for (const [locale, text] of strings) {
        await Bun.write(`public/widget-card.${locale}.js`, text);
    }

    console.log(`public/widget-card.css  ${sizes(css)}`);
    console.log(
        `public/widget-card.js   ${sizes(js)}  (${partials.length} partials + ${BOOT})`,
    );
    for (const [locale, text] of strings) {
        console.log(
            `public/widget-card.${locale}.js${locale === "en" ? "  " : "  "}${sizes(text)}`,
        );
    }
    console.log(`namespaces shipped: ${namespaces.join(", ")}`);
}

await main();
