import { test, expect } from "bun:test";
import { ALT_PAGES, PAGE_ROUTES, SITE_LOCALES, urlFor } from "./routes.js";
import { chromeFor } from "./copy/chrome.js";
import { INDEX } from "./copy/index.js";
import { LOGIN, LOGIN_ERRORS } from "./copy/login.js";

// The SEO "alternative to X" routes, and every locale's version of every
// page, are wired data-driven via src/routes.ts (imported directly here —
// it has no Supabase/side-effecting imports, unlike src/index.ts, so this
// no longer has to regex-scrape route data out of source text the way it
// used to before that extraction).

test("ALT_PAGES is non-empty", () => {
    expect(Object.keys(ALT_PAGES).length).toBeGreaterThan(0);
});

test("PAGE_ROUTES includes every ALT_PAGES entry plus the standalone pages", () => {
    for (const route of Object.keys(ALT_PAGES)) {
        expect(PAGE_ROUTES).toHaveProperty(route);
    }
    for (const suffix of ["", "/tools", "/privacy", "/terms"]) {
        expect(PAGE_ROUTES).toHaveProperty(suffix);
    }
});

// Not every locale has every page translated yet (see src/copy/legal.ts's
// note on Partial<Record<...>> while translation is in progress) — so this
// walks whatever actually exists on disk rather than asserting full 8x11
// coverage, and checks that whatever DOES exist is wired consistently.
// Tightening this to require full coverage is the natural final step once
// every locale's content lands, matching src/copy/legal.ts's own note.
async function fileFor(
    locale: (typeof SITE_LOCALES)[number],
    file: string,
): Promise<string> {
    return locale === "en" ? `./public/${file}` : `./public/${locale}/${file}`;
}

type Existing = {
    locale: (typeof SITE_LOCALES)[number];
    suffix: string;
    path: string;
};

async function existingPages(): Promise<Existing[]> {
    const out: Existing[] = [];
    for (const [suffix, file] of Object.entries(PAGE_ROUTES)) {
        for (const locale of SITE_LOCALES) {
            const path = await fileFor(locale, file);
            if (await Bun.file(path).exists())
                out.push({ locale, suffix, path });
        }
    }
    return out;
}

test("at least the English site exists for every page type", async () => {
    const existing = await existingPages();
    const enSuffixes = new Set(
        existing.filter((e) => e.locale === "en").map((e) => e.suffix),
    );
    for (const suffix of Object.keys(PAGE_ROUTES)) {
        expect(
            enSuffixes.has(suffix),
            `English is missing PAGE_ROUTES suffix "${suffix}"`,
        ).toBe(true);
    }
});

test("every existing page's file is non-empty", async () => {
    const existing = await existingPages();
    expect(existing.length).toBeGreaterThan(0);
    for (const { path } of existing) {
        expect(
            (await Bun.file(path).exists()) && (await Bun.file(path).size) > 0,
            path,
        ).toBe(true);
    }
});

test("every existing page is listed in sitemap.xml with the right locale URL", async () => {
    const existing = await existingPages();
    const sitemap = await Bun.file("./public/sitemap.xml").text();
    for (const { locale, suffix } of existing) {
        const url = urlFor(locale, suffix);
        expect(sitemap, `${url} missing from sitemap.xml`).toContain(
            `<loc>${url}</loc>`,
        );
    }
});

// Only pages produced by the scripts/gen-*.ts pipeline carry page-level
// hreflang/canonical tags (scripts/site-partials.ts's localeHead()) — which
// by now is every page, including public/index.html and public/tools.html
// (both moved off hand-authored HTML onto gen-index.ts/gen-tools.ts).
// This is kept as a generality rather than an unconditional check because
// every generated file always carries scripts/site-partials.ts's
// generatedBanner() HTML comment, which is what distinguishes them — a
// future hand-authored page (there is none today) would fall back to just
// a sitemap entry with hreflang annotations (Google treats those as valid
// on their own), which the "listed in sitemap.xml" test above covers.
async function isGenerated(path: string): Promise<boolean> {
    const html = await Bun.file(path).text();
    return /<!-- Generated by scripts\//.test(html);
}

// The single most common real-world hreflang bug: page A links to page B as
// an alternate, but B doesn't link back to A ("no return tags" in Search
// Console). Checked against the actual rendered HTML's <link rel="alternate
// hreflang> tags, not just the sitemap — a generator bug that only broke the
// per-page tags (scripts/site-partials.ts's localeHead()) while leaving the
// sitemap correct would otherwise slip through.
test("hreflang is fully reciprocal across every generated page", async () => {
    const all = await existingPages();
    const existing = [];
    for (const page of all) {
        if (await isGenerated(page.path)) existing.push(page);
    }
    const bySuffix = new Map<string, Existing[]>();
    for (const e of existing) {
        const list = bySuffix.get(e.suffix) ?? [];
        list.push(e);
        bySuffix.set(e.suffix, list);
    }

    for (const [suffix, pages] of bySuffix) {
        const expectedUrls = new Set(
            pages.map((p) => urlFor(p.locale, suffix)),
        );
        for (const page of pages) {
            const html = await Bun.file(page.path).text();
            // Prettier line-wraps a <link> tag's attributes across multiple
            // lines once it overflows the print width, so this can't assume
            // a single line — match the whole tag body first (non-greedy,
            // across newlines), then pull hreflang/href out of it.
            const hrefs = new Set(
                [...html.matchAll(/<link\s+([\s\S]*?)\/>/g)]
                    .map((m) => m[1]!)
                    .filter(
                        (attrs) =>
                            /rel="alternate"/.test(attrs) &&
                            /hreflang=/.test(attrs),
                    )
                    .map((attrs) => attrs.match(/href="([^"]+)"/)?.[1])
                    .filter((href): href is string => !!href),
            );
            for (const url of expectedUrls) {
                expect(
                    hrefs.has(url),
                    `${page.path} is missing a reciprocal hreflang link to ${url}`,
                ).toBe(true);
            }
        }
    }
});

test("every existing page has a self-referencing canonical, not canonical-to-English", async () => {
    const existing = await existingPages();
    for (const { locale, suffix, path } of existing) {
        const html = await Bun.file(path).text();
        const canonical = [...html.matchAll(/<link\s+([\s\S]*?)\/>/g)]
            .map((m) => m[1]!)
            .find((attrs) => /rel="canonical"/.test(attrs))
            ?.match(/href="([^"]+)"/)?.[1];
        expect(canonical, `${path} has no canonical tag`).toBe(
            urlFor(locale, suffix),
        );
    }
});

// Every AI-translated page discloses that and links back to the English
// original (scripts/site-partials.ts's translationNotice(), added after a
// German page shipped without it) — and English itself must never carry
// the notice, since there's nothing to disclose about itself. Scoped to
// generated pages for the same reason the hreflang/canonical checks above
// are: a page not yet on the generator pipeline has no mechanism to emit
// this at all, which is a known, separate gap (see CLAUDE.md), not this
// guard's job to catch.
test("every generated non-English page discloses it's AI-translated; English never does", async () => {
    const all = await existingPages();
    for (const page of all) {
        if (!(await isGenerated(page.path))) continue;
        const html = await Bun.file(page.path).text();
        if (page.locale === "en") {
            expect(
                html,
                `${page.path} is English but carries a translation notice`,
            ).not.toContain('class="translation-notice"');
        } else {
            expect(
                html,
                `${page.path} is missing the translation-notice disclosure`,
            ).toContain('class="translation-notice"');
        }
    }
});

// ---------------------------------------------------------------------
// The "Live stats" notification badge (liveBadge() in
// scripts/site-partials.ts). It ships in the nav of EVERY page — desktop
// nav and mobile menu — but only the landing page's stats poller ever
// fills it in, so everywhere else it must be inert: present, hidden, and
// carrying that locale's own screen-reader label. The label is the part
// that rots. It is a nav()/footer() string, and those were the one piece
// of chrome that stayed English on every translated page until
// src/copy/chrome.ts existed; a new key added to ChromeCopy without a
// translation is exactly how that happens again. Whitespace is normalized
// because prettier re-wraps these <span>s and a long label lands split
// across two lines.
const collapse = (s: string) => s.replace(/\s+/g, " ").trim();

test("every generated page ships the live-stats badge, hidden", async () => {
    for (const { path } of await existingPages()) {
        if (!(await isGenerated(path))) continue;
        const html = await Bun.file(path).text();
        const badges = html.match(/<span\s+class="nav-badge"[\s\S]*?hidden/g);
        // One in .head-nav, one in .site-menu, one on the hamburger.
        expect(`${path}: ${badges?.length}`).toBe(`${path}: 3`);
        expect(html).toContain('<span class="nav-badge-n">0</span>');
        // Exactly one of the three is the hamburger's, and it is the
        // decorative one — a .vh label inside a button never gets read,
        // since the button's aria-label is its accessible name.
        const decorative = html.match(
            /aria-hidden="true"\s*><span class="nav-badge-n"/g,
        );
        expect(`${path}: ${decorative?.length}`).toBe(`${path}: 1`);
    }
});

// The label is count-sensitive, so what ships is every grammatical form the
// locale has, as data-plural-* attributes setNavBadge picks from at runtime
// (one script, nine locales — it cannot hold a translation of its own). Both
// halves are pinned: the forms must all reach the markup, and the .vh text
// the page renders before any script runs must be the "other" form, which is
// what a count of 0 selects. Asserting only the rendered text would let a
// locale ship with its "one" and "few" forms silently missing from the
// attributes and still pass.
test("the badge's screen-reader label is translated on every locale", async () => {
    for (const { path, locale } of await existingPages()) {
        if (!(await isGenerated(path))) continue;
        const forms = chromeFor(locale).nav.liveStatsBadgeLabel;
        const html = await Bun.file(path).text();
        const found = [
            ...html.matchAll(/<span class="vh"\s*>([\s\S]*?)<\/span/g),
        ].map((m) => collapse(m[1]!));
        expect(`${path}: ${found.includes(collapse(forms.other))}`).toBe(
            `${path}: true`,
        );
        for (const category of ["one", "few", "many", "other"] as const) {
            const form = forms[category];
            if (!form) continue;
            const attr = `data-plural-${category}="${form}"`;
            // Both labelled copies, not just one: the page carries three
            // badges (see the test above), of which the hamburger's is the
            // decorative one and deliberately carries no forms. Counting is
            // what makes this catch a half-regenerated page — an
            // includes() check passes on a file where only the nav copy was
            // rewritten and the menu copy is still the old string.
            const count = html.split(attr).length - 1;
            expect(`${path} [${category}]: ${count}`).toBe(
                `${path} [${category}]: 2`,
            );
        }
    }
});

// Polish and Ukrainian are the reason this whole mechanism exists: their
// noun case turns on the digit class (1 / 2-4 / 5+), and a badge counting
// arrivals since page-open sits in the first two bands almost all of the
// time. A locale that carries "few" but copied it from "many" would render
// grammatically, pass every check above, and still be wrong at the counts
// it actually reaches.
test("the digit-class locales carry three distinct badge forms", async () => {
    for (const locale of ["pl", "uk"] as const) {
        const f = chromeFor(locale).nav.liveStatsBadgeLabel;
        const distinct = new Set([f.one, f.few, f.many]);
        expect(`${locale}: ${distinct.size} of 3`).toBe(`${locale}: 3 of 3`);
    }
});

// The kg / lb toggle in the landing page's live-stats panel. Same failure
// mode as the badge label above and the same reason to pin it: the visible
// text is the symbol, which is identical in every locale, so a locale that
// never translated the accessible names would look completely fine on the
// page and read as English to anyone using a screen reader.
test("the stats unit toggle is labelled in every locale's own words", async () => {
    for (const { path, locale, suffix } of await existingPages()) {
        if (suffix !== "") continue;
        const doc = INDEX[locale];
        expect(`${path}: ${!!doc}`).toBe(`${path}: true`);
        const html = await Bun.file(path).text();
        for (const label of [
            doc!.stats.unitGroupLabel,
            doc!.stats.unitKgLabel,
            doc!.stats.unitLbLabel,
        ]) {
            expect(`${path}: ${html.includes(`aria-label="${label}"`)}`).toBe(
                `${path}: true`,
            );
        }
        // Both buttons, and kg pre-pressed — the markup's resting state has
        // to be the script's default, or a visitor with JS still loading
        // sees neither pill lit.
        expect(html).toContain('data-unit="kg"');
        expect(html).toContain('data-unit="lb"');
    }
});

// The theme switcher, which replaced a two-state button. Two things are
// worth pinning. Its labels: they used to be rewritten by site.js on every
// toggle, in hardcoded English, so a translated page announced the control
// in English the moment anyone used it — they are static and translated
// now, and this is what keeps them that way. And its resting state: the
// markup ships with "system" pressed because that is the setting a visitor
// with nothing stored is actually on. It is NOT true that the pressed pill
// is always the truth before site.js runs — THEME_PREPAINT stamps
// data-theme from localStorage before first paint, so a visitor with a
// stored light/dark override sees the page already in that theme while
// "system" is still the pressed pill until site.js corrects it. That window
// is harmless (the menu holding the switcher is closed), but the resting
// state is a default, not a guarantee.
test("the theme switcher is labelled in every locale's own words", async () => {
    for (const { path, locale } of await existingPages()) {
        if (!(await isGenerated(path))) continue;
        const c = chromeFor(locale).theme;
        const html = await Bun.file(path).text();
        for (const attr of [
            `aria-label="${c.ariaLabel}"`,
            `title="${c.title}"`,
            `aria-label="${c.title}"`,
        ]) {
            expect(`${path}: ${html.includes(attr)}`).toBe(`${path}: true`);
        }
        const modes = [
            ["system", c.system],
            ["light", c.light],
            ["dark", c.dark],
        ] as const;
        for (const [mode, label] of modes) {
            const at = html.indexOf(`data-theme-set="${mode}"`);
            expect(`${path}/${mode}: ${at !== -1}`).toBe(
                `${path}/${mode}: true`,
            );
            const button = html.slice(at, html.indexOf("</button>", at));
            expect(`${path}/${mode}: ${collapse(button).includes(label)}`).toBe(
                `${path}/${mode}: true`,
            );
            // Only System rests pressed — it is the default.
            expect(
                `${path}/${mode}: ${button.includes('aria-pressed="true"')}`,
            ).toBe(`${path}/${mode}: ${mode === "system"}`);
        }
    }
});

// The hamburger's two accessible names. It is one control that toggles, so
// its label has to change with its state — and public/site.js is a single
// static file served to all nine locales, which means it cannot own either
// string. It used to: openMenu()/closeMenu() wrote hardcoded English, so a
// German visitor got "Menü öffnen" until the first tap and "Open menu" for
// the rest of the visit. Both strings live in the markup now — the open one
// as the button's initial aria-label, the close one in data-close-label —
// and the script reads them off the DOM. This pins that both are present
// and in this page's own language, on every generated page.
test("the menu button carries both of its labels, translated", async () => {
    for (const { path, locale } of await existingPages()) {
        if (!(await isGenerated(path))) continue;
        const c = chromeFor(locale);
        const html = await Bun.file(path).text();
        const at = html.indexOf('id="menu-btn"');
        expect(`${path}: ${at !== -1}`).toBe(`${path}: true`);
        const button = collapse(html.slice(at, html.indexOf(">", at)));
        for (const attr of [
            `aria-label="${c.openMenuAriaLabel}"`,
            `data-close-label="${c.closeMenuAriaLabel}"`,
        ]) {
            expect(`${path}: ${button.includes(attr)}`).toBe(`${path}: true`);
        }
    }
});

// The three <nav> landmark names, plus the language menu's own. These are
// the region names a screen reader announces when moving between
// landmarks, and they were hardcoded English on all nine locales —
// "Primary", "Menu", "Footer" — which nothing in a visual review can
// catch, because they never paint. The language menu was worse than
// untranslated: its aria-label sat on a bare <div>, which exposes nothing
// at all, so the label was inert in English too. It has role="group" now
// and reuses languageTitle, matching the .theme-menu beside it.
test("every landmark region is named in the page's own language", async () => {
    for (const { path, locale } of await existingPages()) {
        if (!(await isGenerated(path))) continue;
        const c = chromeFor(locale);
        const html = collapse(await Bun.file(path).text());
        const regions: [string, string][] = [
            [`<nav class="head-nav" aria-label="`, c.landmarks.primaryNav],
            [`<nav aria-label="`, c.landmarks.menu],
            [`<nav class="footer-links" aria-label="`, c.landmarks.footer],
            // Not a nav: a .lang-menu div, inert without role="group".
            [`class="lang-menu" role="group" aria-label="`, c.languageTitle],
        ];
        for (const [open, label] of regions) {
            expect(
                `${path} [${label}]: ${html.includes(open + label + '"')}`,
            ).toBe(`${path} [${label}]: true`);
        }
    }
});

// The OAuth login page. It sits outside every check above because it is
// outside PAGE_ROUTES: it has no fixed URL (src/oauth.ts renders it per
// in-flight session), no sitemap entry and no hreflang, so existingPages()
// never sees it — which is exactly how it stayed English-only on seven
// locales long after the rest of the site was translated. It is also the
// one page whose availability is decided by a file-existence check
// (availableLoginLocales() in src/oauth.ts) rather than by data, so a
// locale whose copy exists but whose page was never regenerated silently
// drops out of the language switcher.
const loginPath = (locale: (typeof SITE_LOCALES)[number]) =>
    locale === "en" ? "./public/login.html" : `./public/${locale}/login.html`;

test("every locale has a built login page, in its own language", async () => {
    for (const locale of SITE_LOCALES) {
        const path = loginPath(locale);
        expect(`${path}: ${await Bun.file(path).exists()}`).toBe(
            `${path}: true`,
        );
        const doc = LOGIN[locale];
        const html = collapse(await Bun.file(path).text());
        // Every visible string except consentNote, which is checked
        // through its two link texts instead — the sentence itself is
        // split by the injected <a> markup.
        for (const line of [
            doc.subtitle,
            doc.googleButton,
            doc.dividerText,
            doc.emailLabel,
            doc.passwordLabel,
            doc.continueButton,
            doc.termsLinkText,
            doc.privacyLinkText,
            doc.newHereNote,
            doc.afterConnectNote,
        ]) {
            expect(`${path} [${line}]: ${html.includes(line)}`).toBe(
                `${path} [${line}]: true`,
            );
        }
        // And not the English original underneath it: a page that renders
        // its own strings AND keeps English ones is a half-regenerated
        // file, which is what a stale public/{locale}/login.html looks
        // like. title is exempt — it's the untranslated product name.
        if (locale !== "en") {
            for (const en of [
                LOGIN.en.subtitle,
                LOGIN.en.newHereNote,
                LOGIN.en.afterConnectNote,
            ]) {
                expect(`${path} [en: ${en}]: ${html.includes(en)}`).toBe(
                    `${path} [en: ${en}]: false`,
                );
            }
        }
    }
});

// This page is a TEMPLATE, not a finished document: renderLoginPage() in
// src/oauth.ts fills these four in per request. A token lost to a
// generator change wouldn't fail a build or a typecheck — it would ship a
// login form whose submit button posts an empty session_id.
test("every login page keeps its four runtime placeholders", async () => {
    for (const locale of SITE_LOCALES) {
        const path = loginPath(locale);
        const html = await Bun.file(path).text();
        for (const token of [
            "{{SESSION_ID}}",
            "{{ERROR}}",
            "{{LANG_SWITCHER}}",
            "{{TRANSLATION_NOTICE}}",
        ]) {
            expect(`${path} ${token}: ${html.includes(token)}`).toBe(
                `${path} ${token}: true`,
            );
        }
    }
});

// The two Google-flow errors never reach a generated file — they're
// substituted into {{ERROR}} at request time — so nothing above would
// notice a locale that shipped a translated page beside English errors.
// (The third error kind, a message from Supabase Auth itself, is
// deliberately untranslated; see LOGIN_ERRORS's doc comment.)
test("every locale's Google sign-in errors are translated", () => {
    for (const locale of SITE_LOCALES) {
        if (locale === "en") continue;
        const errors = LOGIN_ERRORS[locale];
        for (const kind of ["googleCancelled", "googleFailed"] as const) {
            expect(
                `${locale}.${kind}: ${errors[kind] === LOGIN_ERRORS.en[kind]}`,
            ).toBe(`${locale}.${kind}: false`);
        }
    }
});
