// Route and locale data for the public site — deliberately free of any
// import that reaches for Supabase credentials or has other side effects
// (unlike src/index.ts and src/export.ts), so this module is safe to import
// directly from src/index.ts, the site generators under scripts/, AND
// tests. Before this existed, src/alt-pages.test.ts had to regex-scrape
// ALT_PAGES out of src/index.ts's source text instead of importing it.

/** Non-English site locales, in the order the language switcher lists them. */
export const LOCALES = ["de", "es", "fr", "nl", "pl", "it", "uk"] as const;
export type Locale = (typeof LOCALES)[number];

/** English plus every translated locale — every language the site ships in. */
export type SiteLocale = "en" | Locale;
export const SITE_LOCALES: readonly SiteLocale[] = ["en", ...LOCALES];

/** Each locale's own name for itself, for the language switcher. */
export const LOCALE_NAMES: Record<SiteLocale, string> = {
    en: "English",
    de: "Deutsch",
    es: "Español",
    fr: "Français",
    nl: "Nederlands",
    pl: "Polski",
    it: "Italiano",
    uk: "Українська",
};

/**
 * The disclosure shown on every translated (non-English) page — AI
 * translation, no human review pass, with a link back to the English
 * original of the *same* page (built by the caller via
 * `pathFor("en", suffix)`, not embedded here, since this map has no access
 * to which page it's rendering on). Keyed by `Locale`, not `SiteLocale`:
 * English structurally can never have a notice about itself, so the type
 * itself rules out ever needing an `en` entry here.
 *
 * `Partial` for the same reason `src/copy/legal.ts`'s `PRIVACY`/`TERMS`
 * are: translation lands one locale at a time. Tighten to the full
 * `Record<Locale, ...>` alongside those once every locale is present.
 */
export const TRANSLATION_NOTICE: Partial<
    Record<Locale, { text: string; linkText: string }>
> = {
    de: {
        text: "Diese Seite wurde mit KI aus dem Englischen übersetzt und wurde nicht von einer Person überprüft.",
        linkText: "Original auf Englisch lesen",
    },
};

/** IETF BCP 47 tag for `<html lang>` — a bare 2-letter code for every locale
 * here, since none needs a region qualifier (no en-US vs en-GB split, etc). */
export const HTML_LANG: Record<SiteLocale, string> = {
    en: "en",
    de: "de",
    es: "es",
    fr: "fr",
    nl: "nl",
    pl: "pl",
    it: "it",
    uk: "uk",
};

/** Open Graph's `og:locale` wants language_TERRITORY, not a bare tag. */
export const OG_LOCALE: Record<SiteLocale, string> = {
    en: "en_US",
    de: "de_DE",
    es: "es_ES",
    fr: "fr_FR",
    nl: "nl_NL",
    pl: "pl_PL",
    it: "it_IT",
    uk: "uk_UA",
};

// The SEO "alternative to X" comparison pages generated by
// scripts/gen-alternatives.ts. Route (no locale prefix) -> file under
// public/alternatives/. Every locale gets the same slug (see PAGE_ROUTES) —
// only the *file* changes per locale, resolved via public/{locale}/....
export const ALT_PAGES: Record<string, string> = {
    "/alternatives": "alternatives/index.html",
    "/myfitnesspal-mcp": "alternatives/myfitnesspal.html",
    "/cronometer-mcp": "alternatives/cronometer.html",
    "/lose-it-mcp": "alternatives/lose-it.html",
    "/macrofactor-mcp": "alternatives/macrofactor.html",
    "/yazio-mcp": "alternatives/yazio.html",
    "/lifesum-mcp": "alternatives/lifesum.html",
};

// Every page on the site that exists in every locale, as a path suffix
// ("" is the home page) -> file suffix under public/ (English, no prefix)
// or public/{locale}/ (every other locale). ALT_PAGES is spread in so it
// stays the single source of truth for the comparison pages — adding one
// there needs no second edit here.
export const PAGE_ROUTES: Record<string, string> = {
    "": "index.html",
    "/tools": "tools.html",
    "/privacy": "privacy.html",
    "/terms": "terms.html",
    ...ALT_PAGES,
};

export const SITE = "https://nutrition-mcp.com";

/** The site-relative path to a whole page (a PAGE_ROUTES key: "" for home,
 * "/tools", ...) in a given locale — "" + "de" -> "/de", "/tools" + "en"
 * -> "/tools". No trailing slash, matching every route registration. */
export function pathFor(locale: SiteLocale, suffix: string): string {
    const prefix = locale === "en" ? "" : `/${locale}`;
    return `${prefix}${suffix}` || "/";
}

/** The site-relative path to a same-page anchor on the locale's home page
 * — hashPath("de", "how") -> "/de#how", hashPath("en", "how") -> "/#how".
 * Deliberately not just `pathFor(locale, "/#" + id)`: that would insert an
 * extra "/" before the "#" for every non-English locale (prefix already
 * ends the path; the hash rides directly on it, not on a second slash). */
export function hashPath(locale: SiteLocale, id: string): string {
    return `${pathFor(locale, "")}#${id}`;
}

/** The canonical URL for a page suffix (see PAGE_ROUTES keys) in a given
 * locale. No trailing slash on any of them — matches every existing
 * canonical/route on the site ("https://nutrition-mcp.com", ".../tools").
 * Deliberately NOT built from pathFor(): pathFor falls back to "/" for the
 * empty (home) suffix because an <a href=""> would mean "this page", but
 * that fallback would leave the English home canonical as
 * "https://nutrition-mcp.com/" — a trailing slash the rest of the site's
 * canonicals don't have. */
export function urlFor(locale: SiteLocale, suffix: string): string {
    const prefix = locale === "en" ? "" : `/${locale}`;
    return `${SITE}${prefix}${suffix}`;
}
